namespace Koine.Compiler.Emit.TypeScript;

/// <summary>
/// The once-emitted TypeScript runtime support, the analogue of the C# emitter's
/// <c>Koine.Runtime</c> files. It is written to a single <c>runtime.ts</c> at the output
/// root and exports the shared domain primitives every generated module imports:
/// <list type="bullet">
/// <item><c>Decimal</c> — a string-backed exact decimal (money fidelity; a JS
/// <c>number</c> is lossy).</item>
/// <item><c>Instant</c> — a branded ISO-8601 string with <c>Instant.now()</c>.</item>
/// <item><c>DomainInvariantViolationError</c> — thrown when an invariant/illegal transition fails.</item>
/// <item><c>ValueObject</c> — a structural-equality helper (the <c>equals</c> contract).</item>
/// <item><c>Range&lt;T&gt;</c> — a closed interval with containment/overlap.</item>
/// </list>
/// The contents are a fixed string constant (no per-model state), so emission is
/// deterministic and byte-identical across runs.
/// </summary>
internal static class TsRuntime
{
    /// <summary>The relative path of the emitted runtime module (no extension, for imports).</summary>
    public const string ModuleName = "runtime";

    /// <summary>The emitted runtime file path.</summary>
    public const string FileName = "runtime.ts";

    /// <summary>
    /// The shared infrastructure-runtime module (no extension, for imports), emitted once at the output
    /// root only when the opt-in Infrastructure layer is requested (issue #241). It exports the
    /// dependency-light persistence seam (<c>AggregateStore</c> + an in-memory default), the transactional
    /// outbox primitives, and the command-pipeline behavior types every generated infrastructure file
    /// shares — the TS analogue of the C# runtime's infrastructure support.
    /// </summary>
    public const string InfrastructureModuleName = "infrastructure-runtime";

    /// <summary>The emitted infrastructure-runtime file path (off by default; Infrastructure layer only).</summary>
    public const string InfrastructureFileName = "infrastructure-runtime.ts";

    /// <summary>The full source of the runtime module.</summary>
    public const string Source =
        """
        // <auto-generated/>
        // Koine TypeScript runtime: shared domain primitives, emitted once.

        /** Thrown when a domain invariant or illegal state transition is violated. */
        export class DomainInvariantViolationError extends Error {
          readonly typeName: string;
          readonly rule: string;

          constructor(type: string, rule: string) {
            super(`Invariant violated on ${type}: ${rule}`);
            this.name = 'DomainInvariantViolationError';
            this.typeName = type;
            this.rule = rule;
          }
        }

        /**
         * The marker every domain event satisfies: a record of something that happened,
         * stamped with the instant it occurred. An aggregate records these as it mutates
         * (its `domainEvents` collection) — the analogue of the C# `IDomainEvent`.
         */
        export interface DomainEvent {
          readonly occurredOn: Instant;
        }

        /**
         * An exact, string-backed decimal for money fidelity (a JS `number` is lossy).
         * The value is normalized to a canonical string so structural equality is reliable.
         *
         * Construction is string-only on purpose: a JS `number` literal such as `1e-7` or
         * `1e21` would already have lost precision (or be in exponential form) before it
         * reached this constructor. Callers pass the exact textual form. Exponential
         * notation IS accepted in the string (`'1e-7'`, `'1.5E3'`) and normalized to a
         * fixed-point decimal string with no float round-trip.
         */
        export class Decimal {
          readonly value: string;

          constructor(value: string) {
            const normalized = Decimal.normalize(value);
            if (normalized === undefined) {
              throw new DomainInvariantViolationError('Decimal', `not a valid decimal: '${value}'`);
            }
            this.value = normalized;
          }

          /** Builds a Decimal from a plain integer (safe: integers below 2^53 are exact in JS). */
          static fromInt(value: number): Decimal {
            if (!Number.isInteger(value)) {
              throw new DomainInvariantViolationError('Decimal', `not an integer: '${value}'`);
            }
            return new Decimal(value.toString());
          }

          private static normalize(raw: string): string | undefined {
            const trimmed = raw.trim();
            // Accept plain decimals and exponential notation; reject anything else.
            if (!/^[+-]?(\d+(\.\d+)?|\.\d+)([eE][+-]?\d+)?$/.test(trimmed)) {
              return undefined;
            }
            const fixed = Decimal.expandExponential(trimmed);
            const negative = fixed.startsWith('-');
            const digits = fixed.replace(/^[+-]/, '');
            const dot = digits.indexOf('.');
            let intPart = dot < 0 ? digits : digits.slice(0, dot);
            let fracPart = dot < 0 ? '' : digits.slice(dot + 1);
            intPart = intPart.replace(/^0+(?=\d)/, '');
            if (intPart === '') {
              intPart = '0';
            }
            fracPart = fracPart.replace(/0+$/, '');
            const sign = negative && (intPart !== '0' || fracPart !== '') ? '-' : '';
            return fracPart.length > 0 ? `${sign}${intPart}.${fracPart}` : `${sign}${intPart}`;
          }

          /**
           * Expands exponential notation (`1e-7`, `1.5E3`) to a plain fixed-point string by
           * shifting the decimal point, never via a lossy float round-trip. A non-exponential
           * input is returned unchanged.
           */
          private static expandExponential(raw: string): string {
            const m = /^([+-]?)(\d*)(?:\.(\d*))?[eE]([+-]?\d+)$/.exec(raw);
            if (m === null) {
              return raw;
            }
            const sign = m[1] === '-' ? '-' : '';
            const intDigits = m[2] ?? '';
            const fracDigits = m[3] ?? '';
            const exp = parseInt(m[4]!, 10);
            let mantissa = intDigits + fracDigits;
            // Position of the decimal point measured from the left of `mantissa`.
            let point = intDigits.length + exp;
            if (point <= 0) {
              mantissa = '0'.repeat(1 - point) + mantissa;
              point = 1;
            } else if (point >= mantissa.length) {
              mantissa = mantissa + '0'.repeat(point - mantissa.length);
            }
            const intPart = mantissa.slice(0, point);
            const fracPart = mantissa.slice(point);
            return fracPart.length > 0 ? `${sign}${intPart}.${fracPart}` : `${sign}${intPart}`;
          }

          private toBigIntScaled(scale: number): bigint {
            const negative = this.value.startsWith('-');
            const digits = this.value.replace(/^-/, '');
            const dot = digits.indexOf('.');
            const intPart = dot < 0 ? digits : digits.slice(0, dot);
            const fracPart = dot < 0 ? '' : digits.slice(dot + 1);
            const padded = (fracPart + '0'.repeat(scale)).slice(0, scale);
            const combined = intPart + padded;
            const magnitude = BigInt(combined === '' ? '0' : combined);
            return negative ? -magnitude : magnitude;
          }

          private static scaleOf(d: Decimal): number {
            const dot = d.value.indexOf('.');
            return dot < 0 ? 0 : d.value.length - dot - 1;
          }

          private static fromScaled(scaled: bigint, scale: number): Decimal {
            const negative = scaled < 0n;
            let digits = (negative ? -scaled : scaled).toString();
            if (scale === 0) {
              return new Decimal((negative ? '-' : '') + digits);
            }
            digits = digits.padStart(scale + 1, '0');
            const intPart = digits.slice(0, digits.length - scale);
            const fracPart = digits.slice(digits.length - scale);
            return new Decimal(`${negative ? '-' : ''}${intPart}.${fracPart}`);
          }

          add(other: Decimal): Decimal {
            const scale = Math.max(Decimal.scaleOf(this), Decimal.scaleOf(other));
            return Decimal.fromScaled(this.toBigIntScaled(scale) + other.toBigIntScaled(scale), scale);
          }

          subtract(other: Decimal): Decimal {
            const scale = Math.max(Decimal.scaleOf(this), Decimal.scaleOf(other));
            return Decimal.fromScaled(this.toBigIntScaled(scale) - other.toBigIntScaled(scale), scale);
          }

          multiply(other: Decimal | number): Decimal {
            // A `number` factor must be an exact integer scalar (e.g. a quantity); a
            // fractional float would reintroduce the lossiness Decimal exists to avoid.
            const right = typeof other === 'number' ? Decimal.fromInt(other) : other;
            const scale = Decimal.scaleOf(this) + Decimal.scaleOf(right);
            return Decimal.fromScaled(this.toBigIntScaled(Decimal.scaleOf(this)) * right.toBigIntScaled(Decimal.scaleOf(right)), scale);
          }

          compareTo(other: Decimal): number {
            const scale = Math.max(Decimal.scaleOf(this), Decimal.scaleOf(other));
            const a = this.toBigIntScaled(scale);
            const b = other.toBigIntScaled(scale);
            return a < b ? -1 : a > b ? 1 : 0;
          }

          equals(other: Decimal): boolean {
            return this.value === other.value;
          }

          toString(): string {
            return this.value;
          }
        }

        /** A branded ISO-8601 instant: a string that cannot be confused with a plain string. */
        export type Instant = string & { readonly __brand: 'Instant' };

        export const Instant = {
          /** The current instant, as an ISO-8601 UTC string. */
          now(): Instant {
            return new Date().toISOString() as Instant;
          },
          /** Wraps a raw ISO-8601 string as an Instant. */
          of(iso: string): Instant {
            return iso as Instant;
          },
        };

        /** Structural-equality helpers shared by every value object. */
        export function structuralEquals(a: unknown, b: unknown): boolean {
          if (a === b) {
            return true;
          }
          if (a === null || b === null || a === undefined || b === undefined) {
            return false;
          }
          if (typeof (a as { equals?: unknown }).equals === 'function') {
            return (a as { equals(other: unknown): boolean }).equals(b);
          }
          if (Array.isArray(a) && Array.isArray(b)) {
            return a.length === b.length && a.every((x, i) => structuralEquals(x, b[i]));
          }
          if (a instanceof Set && b instanceof Set) {
            if (a.size !== b.size) {
              return false;
            }
            for (const x of a) {
              if (![...b].some((y) => structuralEquals(x, y))) {
                return false;
              }
            }
            return true;
          }
          if (a instanceof Map && b instanceof Map) {
            if (a.size !== b.size) {
              return false;
            }
            for (const [k, v] of a) {
              if (!b.has(k) || !structuralEquals(v, b.get(k))) {
                return false;
              }
            }
            return true;
          }
          return false;
        }

        /** Base for value objects: equality by component value, in declaration order. */
        export abstract class ValueObject {
          protected abstract equalityComponents(): readonly unknown[];

          equals(other: unknown): boolean {
            if (other === null || other === undefined || other.constructor !== this.constructor) {
              return false;
            }
            const mine = this.equalityComponents();
            const theirs = (other as ValueObject).equalityComponents();
            return mine.length === theirs.length && mine.every((c, i) => structuralEquals(c, theirs[i]));
          }
        }

        /**
         * The default total order used by `Range`. Handles the orderable element types Koine
         * maps onto a primitive — `number` (Int), branded `string` (Instant), and a value object
         * exposing `compareTo` (Decimal, and user value objects) — so a `Range<Int>`,
         * `Range<Instant>`, and `Range<Decimal>` all work with no caller-supplied comparator.
         */
        export function defaultCompare<T>(a: T, b: T): number {
          if (a !== null && a !== undefined && typeof (a as { compareTo?: unknown }).compareTo === 'function') {
            return (a as unknown as { compareTo(other: T): number }).compareTo(b);
          }
          if (typeof a === 'number' && typeof b === 'number') {
            return a < b ? -1 : a > b ? 1 : 0;
          }
          if (typeof a === 'string' && typeof b === 'string') {
            return a < b ? -1 : a > b ? 1 : 0;
          }
          throw new DomainInvariantViolationError('Range', 'element type is not orderable');
        }

        /**
         * A closed interval [start, end] over an orderable type, with containment and overlap.
         * The element type need not implement `compareTo`: an optional `compare` function defaults
         * to `defaultCompare`, which orders `number`, `string` (incl. branded `Instant`), and any
         * value exposing `compareTo`. This lets a `Range<number>`/`Range<Instant>` type-check.
         */
        export class Range<T> {
          readonly start: T;
          readonly end: T;
          private readonly compare: (a: T, b: T) => number;

          constructor(start: T, end: T, compare: (a: T, b: T) => number = defaultCompare) {
            this.compare = compare;
            if (compare(start, end) > 0) {
              throw new DomainInvariantViolationError('Range', 'start must be less than or equal to end');
            }
            this.start = start;
            this.end = end;
          }

          /** True when value lies within [start, end] inclusive. */
          contains(value: T): boolean {
            return this.compare(value, this.start) >= 0 && this.compare(value, this.end) <= 0;
          }

          /** True when this range shares at least one point with other. */
          overlaps(other: Range<T>): boolean {
            return this.compare(this.start, other.end) <= 0 && this.compare(other.start, this.end) <= 0;
          }

          equals(other: Range<T>): boolean {
            return structuralEquals(this.start, other.start) && structuralEquals(this.end, other.end);
          }
        }
        """;

    /// <summary>
    /// The full source of the shared infrastructure-runtime module (issue #241). Dependency-light, no
    /// third-party imports, <c>tsc --strict</c>-clean. Emitted once, only when the Infrastructure layer
    /// is requested. Holds the persistence seam (<c>AggregateStore</c> + <c>InMemoryStore</c>), the
    /// transactional-outbox primitives (<c>OutboxMessage</c>, <c>OutboxStore</c>, <c>InMemoryOutboxStore</c>,
    /// <c>IntegrationEventHandler</c>), and the command-pipeline behavior types (<c>PipelineBehavior</c>,
    /// <c>Validator</c>, <c>ValidationError</c>).
    /// </summary>
    public const string InfrastructureSource =
        """
        // <auto-generated/>
        // Koine TypeScript infrastructure runtime: shared, dependency-light persistence,
        // outbox and command-pipeline primitives, emitted once when --layers infrastructure is set.
        import { Instant } from './runtime';

        /**
         * The persistence port over an aggregate root identified by `TId`. The generated
         * `<Root>Repository` is written against this interface, never a concrete store — drop in a
         * database-backed `AggregateStore` to make the generated stack persistent. The default
         * (`InMemoryStore`) keeps aggregates in a Map and is runnable in tests out of the box.
         */
        export interface AggregateStore<TId, TEntity> {
          get(id: TId): Promise<TEntity | undefined>;
          all(): Promise<readonly TEntity[]>;
          add(entity: TEntity): Promise<void>;
          update(entity: TEntity): Promise<void>;
          remove(entity: TEntity): Promise<void>;
        }

        /**
         * The zero-dependency in-memory `AggregateStore`: aggregates live in a Map keyed by a string
         * form of their identity (a strongly-typed id value object's `value`, or the id itself). It is
         * the runnable default and a test double — NOT a production datastore.
         */
        export class InMemoryStore<TId, TEntity> implements AggregateStore<TId, TEntity> {
          private readonly entities = new Map<string, TEntity>();

          constructor(
            private readonly identify: (entity: TEntity) => TId,
            private readonly keyOf: (id: TId) => string = InMemoryStore.defaultKey,
          ) {}

          private static defaultKey(id: unknown): string {
            if (id !== null && typeof id === 'object' && 'value' in id) {
              return String((id as { value: unknown }).value);
            }
            return String(id);
          }

          get(id: TId): Promise<TEntity | undefined> {
            return Promise.resolve(this.entities.get(this.keyOf(id)));
          }

          all(): Promise<readonly TEntity[]> {
            return Promise.resolve<readonly TEntity[]>([...this.entities.values()]);
          }

          add(entity: TEntity): Promise<void> {
            this.entities.set(this.keyOf(this.identify(entity)), entity);
            return Promise.resolve();
          }

          update(entity: TEntity): Promise<void> {
            this.entities.set(this.keyOf(this.identify(entity)), entity);
            return Promise.resolve();
          }

          remove(entity: TEntity): Promise<void> {
            this.entities.delete(this.keyOf(this.identify(entity)));
            return Promise.resolve();
          }
        }

        /**
         * A persisted, serialized integration event awaiting dispatch (the transactional-outbox row).
         * Written in the same `saveChanges` as the aggregate change so an event is never lost on commit;
         * `processedOn` is stamped once the dispatcher has delivered it.
         */
        export class OutboxMessage {
          readonly id: string;
          readonly type: string;
          readonly payload: string;
          readonly occurredOn: Instant;
          processedOn: Instant | undefined;

          constructor(type: string, payload: string, occurredOn: Instant = Instant.now()) {
            this.id = OutboxMessage.newId();
            this.type = type;
            this.payload = payload;
            this.occurredOn = occurredOn;
            this.processedOn = undefined;
          }

          /** Serializes an integration event into an opaque outbox row (type name + JSON payload). */
          static from(integrationEvent: object): OutboxMessage {
            const typeName = (integrationEvent as { constructor: { name: string } }).constructor.name;
            return new OutboxMessage(typeName, JSON.stringify(integrationEvent));
          }

          private static newId(): string {
            return typeof crypto !== 'undefined' && 'randomUUID' in crypto
              ? crypto.randomUUID()
              : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
          }
        }

        /** The persistence port for outbox rows; `InMemoryOutboxStore` is the runnable default. */
        export interface OutboxStore {
          add(message: OutboxMessage): Promise<void>;
          unprocessed(): Promise<readonly OutboxMessage[]>;
          markProcessed(message: OutboxMessage): Promise<void>;
        }

        /** The zero-dependency in-memory `OutboxStore`: rows live in an array, ordered by insertion. */
        export class InMemoryOutboxStore implements OutboxStore {
          private readonly messages: OutboxMessage[] = [];

          add(message: OutboxMessage): Promise<void> {
            this.messages.push(message);
            return Promise.resolve();
          }

          unprocessed(): Promise<readonly OutboxMessage[]> {
            return Promise.resolve<readonly OutboxMessage[]>(this.messages.filter((m) => m.processedOn === undefined));
          }

          markProcessed(message: OutboxMessage): Promise<void> {
            message.processedOn = Instant.now();
            return Promise.resolve();
          }
        }

        /**
         * Delivers a drained integration event (as its persisted outbox row) to its in-process
         * subscribers. The publisher stays decoupled from its subscribers: the consumer implements this
         * single seam to fan out to their handlers.
         */
        export interface IntegrationEventHandler {
          handle(message: OutboxMessage): Promise<void>;
        }

        /**
         * One step in the command pipeline: it receives the request and a `next` continuation and either
         * short-circuits (e.g. a failed validation) or delegates to `next`. The MediatR-style behavior
         * the C# emitter renders as `IPipelineBehavior`, expressed idiomatically as a function.
         */
        export type PipelineBehavior<TRequest, TResponse> = (
          request: TRequest,
          next: () => Promise<TResponse>,
        ) => Promise<TResponse>;

        /** A request validator: returns the validation errors for a request (empty when valid). */
        export interface Validator<TRequest> {
          validate(request: TRequest): readonly string[];
        }

        /** Thrown by the validation behavior when a request fails one or more validators. */
        export class ValidationError extends Error {
          readonly errors: readonly string[];

          constructor(errors: readonly string[]) {
            super(`Validation failed: ${errors.join('; ')}`);
            this.name = 'ValidationError';
            this.errors = errors;
          }
        }

        /** Runs a request through the given behaviors (outermost first) ending at `handler`. */
        export function runPipeline<TRequest, TResponse>(
          behaviors: readonly PipelineBehavior<TRequest, TResponse>[],
          request: TRequest,
          handler: () => Promise<TResponse>,
        ): Promise<TResponse> {
          let next = handler;
          for (let i = behaviors.length - 1; i >= 0; i--) {
            const behavior = behaviors[i]!;
            const downstream = next;
            next = () => behavior(request, downstream);
          }
          return next();
        }
        """;
}
