using System.Text;
using Koine.Compiler.Ast;

namespace Koine.Compiler.Emit.TypeScript;

/// <summary>
/// The anti-corruption-layer slice of <see cref="TypeScriptEmitter"/> (R14.2, TS parity): mirrors the
/// C# emitter's <c>I&lt;Up&gt;To&lt;Down&gt;Translator</c>. For each context-map relation of kind
/// <see cref="ContextRelationKind.AntiCorruptionLayer"/> that carries an <c>acl { … }</c> mapping
/// block, this emits one translator interface into the downstream context with a
/// <c>translate&lt;LocalType&gt;(source): &lt;LocalType&gt;</c> method per mapping (upstream type →
/// local type). A pure abstraction; no runtime behavior, exactly like the C# seam.
/// </summary>
public sealed partial class TypeScriptEmitter
{
    /// <summary>
    /// Emits the anti-corruption-layer translator interface for one ACL relation: an
    /// <c>export interface I&lt;Up&gt;To&lt;Down&gt;Translator</c> in the downstream context's
    /// <c>abstractions/</c> folder, with one <c>translate&lt;LocalType&gt;</c> method per mapping.
    /// Each method maps the upstream type to the local type (the C# emitter's <c>Translate</c>
    /// overloads, disambiguated by the local type name since TS interfaces can't overload). Both the
    /// upstream and local types are imported from their generated modules — the import resolution
    /// reuses the same <see cref="TsTypeLocation"/> table the rest of the emitter uses, so an
    /// upstream type that belongs to an emitted context (e.g. a Gateway) resolves to its real module,
    /// matching the C# emitter's fully-qualified reference.
    /// </summary>
    private EmittedFile EmitAclTranslator(TsEmitContext emit, ContextRelation r)
    {
        var upstream = TypeScriptNaming.ToPascalCase(r.Upstream);
        var downstream = TypeScriptNaming.ToPascalCase(r.Downstream);
        var iface = $"I{upstream}To{downstream}Translator";
        var ns = r.Downstream;
        var folder = FolderFor(ns) + "/" + KindFolder.Abstractions;

        // Resolve the import module for a type as declared in a given context, preferring a location
        // in that context (mirrors Assemble's per-context preference). Both the upstream and local
        // types are imported from the modules they actually emit into.
        string? ModuleFor(string context, string typeName)
        {
            TsTypeLocation? match = null;
            foreach (TsTypeLocation loc in emit.TypeLocations)
            {
                if (loc.ExportName == typeName && loc.Context == context)
                {
                    return loc.ModulePath;
                }

                if (loc.ExportName == typeName)
                {
                    match ??= loc;
                }
            }

            return match?.ModulePath;
        }

        var imports = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var methods = new List<(string LocalType, string UpstreamType)>();
        foreach (AclMapping m in r.AclMappings)
        {
            var localType = TypeScriptNaming.ToPascalCase(m.LocalType);
            var upstreamType = TypeScriptNaming.ToPascalCase(m.UpstreamType);

            if (ModuleFor(m.LocalContext, localType) is { } localModule)
            {
                imports[localType] = ImportSpecifier(folder, localModule);
            }

            if (ModuleFor(m.UpstreamContext, upstreamType) is { } upstreamModule)
            {
                imports[upstreamType] = ImportSpecifier(folder, upstreamModule);
            }

            methods.Add((localType, upstreamType));
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        foreach (var (symbol, specifier) in imports)
        {
            sb.Append("import { ").Append(symbol).Append(" } from '").Append(specifier).Append("';\n");
        }
        if (imports.Count > 0)
        {
            sb.Append('\n');
        }

        WriteDoc(sb, $"Anti-corruption translator from upstream context {r.Upstream} into {r.Downstream}.", "");
        sb.Append("export interface ").Append(iface).Append(" {\n");
        var first = true;
        foreach (var (localType, upstreamType) in methods)
        {
            if (!first)
            {
                sb.Append('\n');
            }

            first = false;
            sb.Append(Indent).Append("translate").Append(localType).Append("(source: ")
              .Append(upstreamType).Append("): ").Append(localType).Append(";\n");
        }
        sb.Append("}\n");

        return new EmittedFile(PathFor(ns, KindFolder.Abstractions, iface), sb.ToString());
    }
}
