using System.Text;
using System.Text.RegularExpressions;
using Koine.Compiler.Ast;

namespace Koine.Compiler.Emit.TypeScript;

/// <summary>
/// The orchestration support for <see cref="TypeScriptEmitter"/>: per-run state, file layout
/// (namespace → folder, DDD kind subfolders), module-import resolution (each file imports the
/// runtime symbols and the sibling user types it references), and small shared formatting helpers.
/// </summary>
public sealed partial class TypeScriptEmitter
{
    /// <summary>The immutable per-emit state threaded through every emit method (the emitter stays reentrant).</summary>
    internal sealed record TsEmitContext(
        ModelIndex Index,
        IReadOnlySet<string> AdditiveNeeds,
        IReadOnlyDictionary<string, IReadOnlySet<string>> ScalarNeeds,
        IReadOnlyList<string> ContextNames,
        IReadOnlyList<TsTypeLocation> TypeLocations,
        IReadOnlyDictionary<string, string> EnumMemberToType);

    /// <summary>
    /// Where an emitted user type lives: the import module path (no extension), the primary export
    /// name, and any auxiliary exports a referencing file may need (an enum's <c>&lt;Name&gt;Member</c>
    /// type and <c>&lt;Name&gt;Match</c>/<c>&lt;Name&gt;FromName</c>… helpers; an ID's <c>&lt;Name&gt;New</c>).
    /// </summary>
    internal readonly record struct TsTypeLocation(string Context, string ModulePath, string ExportName, IReadOnlyList<string> AuxExports);

    // ----------------------------------------------------------------------
    // File layout
    // ----------------------------------------------------------------------

    private static class KindFolder
    {
        public const string Root = "";
        public const string Entities = "entities";
        public const string ValueObjects = "value-objects";
        public const string Enums = "enums";
        public const string Events = "events";
    }

    private static string FolderFor(string ns) => ns.Replace('.', '/');

    /// <summary>The output path for a type's file: namespace folder, optional kind subfolder, <c>Name.ts</c>.</summary>
    private static string PathFor(string ns, string kindFolder, string name)
    {
        var folder = FolderFor(ns);
        return kindFolder.Length == 0 ? $"{folder}/{name}.ts" : $"{folder}/{kindFolder}/{name}.ts";
    }

    /// <summary>The import module path (no extension) a type's file is reachable at, for cross-file imports.</summary>
    private static string ModulePathFor(string ns, string kindFolder, string name)
    {
        var folder = FolderFor(ns);
        return kindFolder.Length == 0 ? $"{folder}/{name}" : $"{folder}/{kindFolder}/{name}";
    }

    private static string ContextOf(string ns)
    {
        var dot = ns.IndexOf('.');
        return dot < 0 ? ns : ns[..dot];
    }

    // ----------------------------------------------------------------------
    // Module imports
    // ----------------------------------------------------------------------

    /// <summary>The runtime symbols any file may reference, and the order they import in.</summary>
    private static readonly IReadOnlyList<string> RuntimeSymbols =
        new[] { "DomainInvariantViolationError", "Decimal", "Instant", "structuralEquals", "ValueObject", "Range", "defaultCompare" };

    private static readonly Regex IdentifierRegex = new(@"\b[A-Za-z_][A-Za-z0-9_]*\b", RegexOptions.Compiled);

    /// <summary>
    /// Wraps a rendered file body with the imports it needs and an <c>// &lt;auto-generated/&gt;</c>
    /// banner. The set of imports is derived from the identifiers that actually appear in the body
    /// (the same data-driven approach as the C# <c>UsingCollector</c>): runtime symbols import from
    /// the once-emitted <c>runtime</c> module; sibling user types import from their own module via a
    /// relative path computed from this file's folder.
    /// </summary>
    private string Assemble(TsEmitContext emit, string ns, string kindFolder, string body)
    {
        var folder = kindFolder.Length == 0 ? FolderFor(ns) : $"{FolderFor(ns)}/{kindFolder}";
        var present = new HashSet<string>(StringComparer.Ordinal);
        foreach (Match m in IdentifierRegex.Matches(body))
        {
            present.Add(m.Value);
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");

        // Runtime imports.
        var runtime = RuntimeSymbols.Where(present.Contains).ToList();
        if (runtime.Count > 0)
        {
            sb.Append("import { ").Append(string.Join(", ", runtime)).Append(" } from '")
              .Append(RelativeImport(folder, TsRuntime.ModuleName)).Append("';\n");
        }

        // Cross-file user-type imports: any known type symbol that appears in the body but is NOT
        // declared by this file. Ordered by symbol for deterministic output.
        var imports = new SortedDictionary<string, string>(StringComparer.Ordinal);

        // Determine which symbols this file declares (so it never imports itself).
        var declaredHere = new HashSet<string>(StringComparer.Ordinal);
        foreach (Match m in DeclRegex.Matches(body))
        {
            declaredHere.Add(m.Groups[1].Value);
        }

        // For every needed symbol, pick the declaring module — preferring a location in THIS file's
        // own context (a shared type such as `Money` is emitted per context; a reference resolves to
        // the local copy, never a sibling context's).
        var thisContext = ContextOf(ns);
        var bySymbol = new Dictionary<string, List<TsTypeLocation>>(StringComparer.Ordinal);
        foreach (TsTypeLocation loc in emit.TypeLocations)
        {
            foreach (var symbol in loc.AuxExports.Prepend(loc.ExportName))
            {
                if (!bySymbol.TryGetValue(symbol, out List<TsTypeLocation>? list))
                {
                    bySymbol[symbol] = list = new List<TsTypeLocation>();
                }
                list.Add(loc);
            }
        }

        foreach (var (symbol, candidates) in bySymbol.OrderBy(kv => kv.Key, StringComparer.Ordinal))
        {
            if (declaredHere.Contains(symbol) || !present.Contains(symbol))
            {
                continue;
            }
            TsTypeLocation chosen = candidates.FirstOrDefault(c => c.Context == thisContext, candidates[0]);
            imports[symbol] = RelativeImport(folder, chosen.ModulePath);
        }

        // Group imports by module so a module imported for several symbols emits one statement.
        foreach (var group in imports.GroupBy(kv => kv.Value).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var symbols = group.Select(kv => kv.Key).OrderBy(s => s, StringComparer.Ordinal);
            sb.Append("import { ").Append(string.Join(", ", symbols)).Append(" } from '").Append(group.Key).Append("';\n");
        }

        if (runtime.Count > 0 || imports.Count > 0)
        {
            sb.Append('\n');
        }

        sb.Append(body);
        if (!body.EndsWith('\n'))
        {
            sb.Append('\n');
        }
        return sb.ToString();
    }

    /// <summary>Matches the names this file exports, so it never imports its own symbols.</summary>
    private static readonly Regex DeclRegex = new(
        @"export (?:class|interface|const|type|function) ([A-Za-z_][A-Za-z0-9_]*)",
        RegexOptions.Compiled);

    /// <summary>A relative ESM import specifier from <paramref name="fromFolder"/> to <paramref name="toModule"/>.</summary>
    private static string RelativeImport(string fromFolder, string toModule)
    {
        string[] from = fromFolder.Length == 0 ? Array.Empty<string>() : fromFolder.Split('/');
        string[] to = toModule.Split('/');

        var common = 0;
        while (common < from.Length && common < to.Length - 1 && from[common] == to[common])
        {
            common++;
        }

        var ups = from.Length - common;
        var parts = new List<string>();
        for (var i = 0; i < ups; i++)
        {
            parts.Add("..");
        }
        for (var i = common; i < to.Length; i++)
        {
            parts.Add(to[i]);
        }

        var path = string.Join("/", parts);
        return path.StartsWith('.') ? path : "./" + path;
    }

    // ----------------------------------------------------------------------
    // Type-location map (typeName -> import module + export name)
    // ----------------------------------------------------------------------

    private static IReadOnlyList<TsTypeLocation> BuildTypeNamespaces(KoineModel model)
    {
        var locations = new List<TsTypeLocation>();
        ModelIndex index = new SemanticModel(model).Index;

        foreach (ContextNode ctx in model.Contexts)
        {
            var idsHere = new HashSet<string>(StringComparer.Ordinal);
            foreach (TypeDecl type in ctx.AllTypeDecls())
            {
                var ns = ModelIndex.NamespaceOf(ctx.Name, type.ModulePath);
                Record(locations, ctx.Name, type, ns);
                if (type is EntityDecl entity)
                {
                    var idName = TypeScriptNaming.ToPascalCase(entity.IdentityName);
                    locations.Add(new TsTypeLocation(ctx.Name, ModulePathFor(ns, KindFolder.ValueObjects, idName), idName, new[] { idName + "New" }));
                    idsHere.Add(entity.IdentityName);
                }
            }

            // Unowned IDs default into the context root namespace.
            foreach (var idName in OrderedUnownedIds(ctx, index))
            {
                if (idsHere.Add(idName))
                {
                    var ts = TypeScriptNaming.ToPascalCase(idName);
                    locations.Add(new TsTypeLocation(ctx.Name, ModulePathFor(ctx.Name, KindFolder.ValueObjects, ts), ts, new[] { ts + "New" }));
                }
            }
        }

        return locations;
    }

    private static void Record(List<TsTypeLocation> locations, string context, TypeDecl type, string ns)
    {
        switch (type)
        {
            case ValueObjectDecl vo:
                Add(locations, context, vo.Name, ns, KindFolder.ValueObjects);
                break;
            case EnumDecl en:
                Add(locations, context, en.Name, ns, KindFolder.Enums, EnumAuxExports(TypeScriptNaming.ToPascalCase(en.Name)));
                break;
            case EntityDecl entity:
                Add(locations, context, entity.Name, ns, KindFolder.Entities);
                break;
            case EventDecl ev:
                Add(locations, context, ev.Name, ns, KindFolder.Events);
                break;
        }
    }

    /// <summary>An enum module's auxiliary exports: the member type and the smart-enum helpers.</summary>
    private static IReadOnlyList<string> EnumAuxExports(string ts) => new[]
    {
        ts + "Member", ts + "Name", ts + "All",
        ts + "Match", ts + "Switch",
        ts + "FromName", ts + "FromValue", ts + "TryFromName", ts + "TryFromValue",
    };

    private static void Add(List<TsTypeLocation> locations, string context, string name, string ns, string kindFolder, IReadOnlyList<string>? aux = null)
    {
        var ts = TypeScriptNaming.ToPascalCase(name);
        locations.Add(new TsTypeLocation(context, ModulePathFor(ns, kindFolder, ts), ts, aux ?? Array.Empty<string>()));
    }

    // ----------------------------------------------------------------------
    // ID ownership (mirrors the C# emitter's unowned-id logic, trimmed for TS scope)
    // ----------------------------------------------------------------------

    private static IEnumerable<string> OrderedUnownedIds(ContextNode ctx, ModelIndex index)
    {
        var owned = new HashSet<string>(ctx.AllEntities().Select(e => e.IdentityName), StringComparer.Ordinal);
        var seen = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var idName in index.IdTypeNames)
        {
            if (!owned.Contains(idName) && IsReferencedInContext(ctx, idName))
            {
                seen.Add(idName);
            }
        }
        return seen;
    }

    private static bool IsReferencedInContext(ContextNode ctx, string idName)
    {
        foreach (TypeDecl t in ctx.AllTypeDecls())
        {
            IEnumerable<TypeRef> types = t switch
            {
                ValueObjectDecl v => v.Members.Select(m => m.Type),
                EntityDecl e => e.Members.Select(m => m.Type)
                    .Concat(e.Commands.SelectMany(c => c.Parameters.Select(p => p.Type)))
                    .Concat(e.Factories.SelectMany(f => f.Parameters.Select(p => p.Type))),
                EventDecl ev => ev.Members.Select(m => m.Type),
                _ => Array.Empty<TypeRef>()
            };
            if (types.Any(tr => TypeRefMentions(tr, idName)))
            {
                return true;
            }
        }
        return false;
    }

    private static bool TypeRefMentions(TypeRef type, string name) =>
        type.Name == name
        || (type.Element is not null && TypeRefMentions(type.Element, name))
        || (type.Value is not null && TypeRefMentions(type.Value, name));

    // ----------------------------------------------------------------------
    // Enum member map (member name -> owning enum), for translator qualification
    // ----------------------------------------------------------------------

    private static Dictionary<string, string> BuildEnumMemberMap(KoineModel model)
    {
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (ContextNode ctx in model.Contexts)
        {
            foreach (EnumDecl @enum in ctx.AllTypeDecls().OfType<EnumDecl>())
            {
                foreach (var member in @enum.MemberNames)
                {
                    map.TryAdd(member, @enum.Name);
                }
            }
        }
        return map;
    }

    // ----------------------------------------------------------------------
    // Formatting helpers
    // ----------------------------------------------------------------------

    /// <summary>Renders a target-agnostic doc string as a TSDoc block comment.</summary>
    private static void WriteDoc(StringBuilder sb, string? doc, string indent)
    {
        if (string.IsNullOrEmpty(doc))
        {
            return;
        }

        var lines = doc.Split('\n');
        if (lines.Length == 1)
        {
            sb.Append(indent).Append("/** ").Append(lines[0]).Append(" */\n");
            return;
        }

        sb.Append(indent).Append("/**\n");
        foreach (var line in lines)
        {
            sb.Append(indent).Append(" * ").Append(line).Append('\n');
        }
        sb.Append(indent).Append(" */\n");
    }

    /// <summary>A TS string literal for a guard/invariant rule message.</summary>
    private static string RuleLiteral(string rule) =>
        "'" + rule.Replace("\\", "\\\\").Replace("'", "\\'") + "'";
}
