using System.Text;
using Koine.Compiler.Ast;

namespace Koine.Compiler.Emit.TypeScript;

/// <summary>
/// The Unit-of-Work slice of <see cref="TypeScriptEmitter"/> (R12.1, TS parity): the context's
/// transactional seam over its aggregate repositories. Mirrors the C# emitter's
/// <c>IUnitOfWork</c> — one repository-typed property per aggregate root plus an async
/// <c>saveChangesAsync</c>. A pure abstraction; no infrastructure type appears.
/// </summary>
public sealed partial class TypeScriptEmitter
{
    /// <summary>
    /// Emits the context's <c>IUnitOfWork</c> (R12.1): one <c>readonly</c> property per aggregate
    /// (in declaration order), typed as the aggregate root's generated <c>I&lt;Root&gt;Repository</c>
    /// interface and imported from its module, plus <c>saveChangesAsync(): Promise&lt;void&gt;</c>.
    /// Lives in the context-root <c>abstractions/</c> folder, mirroring the C# emitter's
    /// <c>Abstractions</c> placement.
    /// </summary>
    private EmittedFile EmitUnitOfWork(TsEmitContext emit, string contextName, IReadOnlyList<AggregateDecl> aggregates)
    {
        const string fileName = "IUnitOfWork";
        var ns = contextName;
        var folder = FolderFor(ns) + "/" + KindFolder.Abstractions;

        // Resolve each aggregate's repository interface name + the module path it is emitted at
        // (the repository lives in the aggregate's namespace, which may be a module sub-namespace),
        // then compute the import specifier from THIS file's folder.
        var imports = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var properties = new List<(string PropertyName, string RepoType)>();
        foreach (AggregateDecl agg in aggregates)
        {
            EntityDecl? root = agg.RootEntity();
            if (root is null)
            {
                continue;
            }

            var rootName = TypeScriptNaming.ToPascalCase(root.Name);
            var repoType = $"I{rootName}Repository";
            var aggNs = ModelIndex.NamespaceOf(contextName, agg.ModulePath);
            var modulePath = ModulePathFor(aggNs, KindFolder.Repositories, repoType);
            imports[repoType] = ImportSpecifier(folder, modulePath);
            properties.Add((TypeScriptNaming.ToCamelCase(Pluralize(rootName)), repoType));
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        foreach (var (symbol, specifier) in imports)
        {
            sb.Append("import { ").Append(symbol).Append(" } from '").Append(specifier).Append("';\n");
        }
        if (imports.Count > 0)
        {
            sb.Append('\n');
        }

        WriteDoc(sb, "Transactional boundary over this context's aggregate repositories.", "");
        sb.Append("export interface IUnitOfWork {\n");
        foreach (var (propertyName, repoType) in properties)
        {
            sb.Append(Indent).Append("readonly ").Append(propertyName).Append(": ").Append(repoType).Append(";\n");
        }
        sb.Append('\n');
        sb.Append(Indent).Append("saveChangesAsync(): Promise<void>;\n");
        sb.Append("}\n");

        return new EmittedFile(PathFor(ns, KindFolder.Abstractions, fileName), sb.ToString());
    }

    /// <summary>A small English pluralizer for repository property names (Order -&gt; Orders, Category -&gt; Categories).</summary>
    private static string Pluralize(string name)
    {
        if (name.Length == 0)
        {
            return name;
        }

        if (name.EndsWith("s", StringComparison.Ordinal) || name.EndsWith("x", StringComparison.Ordinal)
            || name.EndsWith("z", StringComparison.Ordinal) || name.EndsWith("ch", StringComparison.Ordinal)
            || name.EndsWith("sh", StringComparison.Ordinal))
        {
            return name + "es";
        }

        if (name.Length >= 2 && char.ToLowerInvariant(name[^1]) == 'y'
            && "aeiou".IndexOf(char.ToLowerInvariant(name[^2])) < 0)
        {
            return name[..^1] + "ies";
        }

        return name + "s";
    }
}
