namespace Koine.Compiler.Emit.Python;

/// <summary>
/// The once-emitted Python runtime support, the analogue of the C# emitter's <c>Koine.Runtime</c>
/// files and the TypeScript emitter's <c>runtime.ts</c>. It is written to a single
/// <c>koine_runtime.py</c> at the output root and provides the shared domain primitives every
/// generated module imports:
/// <list type="bullet">
/// <item><c>DomainInvariantViolationError</c> — raised when an invariant or illegal state
/// transition fails (carries the offending type name and rule).</item>
/// <item><c>ConcurrencyConflictError</c> — raised on an optimistic-concurrency version mismatch.</item>
/// <item><c>Instant</c> — a helper exposing <c>now()</c> → a timezone-aware UTC <c>datetime</c>.</item>
/// <item><c>Range[T]</c> — a closed interval over an orderable type, with containment/overlap.</item>
/// <item><c>AggregateRoot</c>/<c>QueryHandler</c> — structural <c>Protocol</c>s.</item>
/// </list>
/// The contents are a fixed string constant (no per-model state), so emission is deterministic and
/// byte-identical across runs. The module is dependency-free (stdlib only) and <c>mypy --strict</c>-clean.
/// </summary>
internal static class PyRuntime
{
    /// <summary>The emitted runtime file path, at the output root.</summary>
    public const string FileName = "koine_runtime.py";

    /// <summary>The dotted import name of the runtime module (<c>from koine_runtime import …</c>).</summary>
    public const string ModuleName = "koine_runtime";

    /// <summary>The emitted infrastructure-runtime file path (off by default; Infrastructure layer only).</summary>
    public const string InfrastructureFileName = "koine_infrastructure.py";

    /// <summary>The dotted import name of the infrastructure-runtime module (issue #241).</summary>
    public const string InfrastructureModuleName = "koine_infrastructure";

    /// <summary>The full source of the runtime module.</summary>
    public const string Source =
        """"
        # <auto-generated/>
        # Koine Python runtime: shared domain primitives, emitted once.
        from __future__ import annotations

        from datetime import datetime, timezone
        from decimal import Decimal
        from typing import Any, Callable, Generic, Iterable, Protocol, TypeVar, runtime_checkable


        class DomainInvariantViolationError(Exception):
            """Raised when a domain invariant or illegal state transition is violated."""

            type_name: str
            rule: str

            def __init__(self, type_name: str, rule: str) -> None:
                super().__init__(f"Invariant violated on {type_name}: {rule}")
                self.type_name = type_name
                self.rule = rule


        class ConcurrencyConflictError(Exception):
            """Raised when an optimistic-concurrency version check fails on a versioned aggregate."""

            type_name: str
            expected: int
            actual: int

            def __init__(self, type_name: str, expected: int, actual: int) -> None:
                super().__init__(
                    f"Concurrency conflict on {type_name}: expected version {expected}, was {actual}"
                )
                self.type_name = type_name
                self.expected = expected
                self.actual = actual


        class Instant:
            """Time source for `now`-typed defaults: a timezone-aware UTC instant."""

            @staticmethod
            def now() -> datetime:
                """The current instant, as a timezone-aware UTC `datetime`."""
                return datetime.now(timezone.utc)


        class _Comparable(Protocol):
            """An element type orderable via `<` / `<=` (the default `Range` ordering).

            The comparison parameter is typed `Any` (not `object`) so a stdlib orderable such as
            `datetime` — whose `__lt__`/`__le__` accept only their own type, not arbitrary `object`
            — structurally satisfies the protocol (the typeshed `SupportsRichComparison` approach).
            """

            def __lt__(self, other: Any) -> bool: ...

            def __le__(self, other: Any) -> bool: ...


        T = TypeVar("T", bound=_Comparable)


        class Range(Generic[T]):
            """A closed interval [start, end] over an orderable type, with containment and overlap.

            Ordering defaults to the element type's `<=`; an explicit `compare` callable (returning
            a negative/zero/positive int, like `functools.cmp_to_key`) may be supplied for element
            types that are not directly orderable.
            """

            start: T
            end: T

            def __init__(
                self, start: T, end: T, compare: Callable[[T, T], int] | None = None
            ) -> None:
                self._compare = compare
                if self._cmp(start, end) > 0:
                    raise DomainInvariantViolationError(
                        "Range", "start must be less than or equal to end"
                    )
                self.start = start
                self.end = end

            def _cmp(self, a: T, b: T) -> int:
                if self._compare is not None:
                    return self._compare(a, b)
                if a < b:
                    return -1
                if b < a:
                    return 1
                return 0

            def contains(self, value: T) -> bool:
                """True when `value` lies within [start, end] inclusive."""
                return self._cmp(value, self.start) >= 0 and self._cmp(value, self.end) <= 0

            def overlaps(self, other: Range[T]) -> bool:
                """True when this range shares at least one point with `other`."""
                return self._cmp(self.start, other.end) <= 0 and self._cmp(other.start, self.end) <= 0

            def __eq__(self, other: object) -> bool:
                if not isinstance(other, Range):
                    return NotImplemented
                return bool(self.start == other.start and self.end == other.end)

            def __hash__(self) -> int:
                return hash((self.start, self.end))


        @runtime_checkable
        class AggregateRoot(Protocol):
            """The marker every aggregate root satisfies: it exposes its identity."""

            @property
            def id(self) -> object: ...


        TQuery = TypeVar("TQuery", contravariant=True)
        TResult = TypeVar("TResult", covariant=True)


        @runtime_checkable
        class QueryHandler(Protocol[TQuery, TResult]):
            """Handles a read-side query, returning its result (the CQRS query seam)."""

            def handle(self, query: TQuery) -> TResult: ...


        TFold = TypeVar("TFold", bound=_Comparable)


        class _Addable(Protocol):
            """An element type that folds under `+` to its own type (the `sum` element bound).

            Both `Decimal` and the generated value objects (whose demand-driven `__add__` returns
            their own type) structurally satisfy this, so one generic `koine_sum` covers a sum of
            money amounts and a sum of `Money` value objects alike. `other` is typed `Any` (not
            `object`) so an `__add__` accepting only its own type still satisfies the protocol.
            """

            def __add__(self: TAdd, other: Any) -> TAdd: ...


        TAdd = TypeVar("TAdd", bound=_Addable)


        def koine_min(values: Iterable[TFold]) -> TFold:
            """The minimum element, raising a domain error on an empty collection (no value)."""
            it = iter(values)
            try:
                result = next(it)
            except StopIteration:
                raise DomainInvariantViolationError(
                    "collection", "cannot take min of an empty collection (no value)"
                ) from None
            for value in it:
                if value < result:
                    result = value
            return result


        def koine_max(values: Iterable[TFold]) -> TFold:
            """The maximum element, raising a domain error on an empty collection (no value)."""
            it = iter(values)
            try:
                result = next(it)
            except StopIteration:
                raise DomainInvariantViolationError(
                    "collection", "cannot take max of an empty collection (no value)"
                ) from None
            for value in it:
                if result < value:
                    result = value
            return result


        def koine_sum(values: Iterable[TAdd]) -> TAdd:
            """The sum of a collection, folding under `+` from the first element.

            Generic over any addable element — a `Decimal` amount or a value object whose
            `__add__` returns its own type — so the result keeps the element's type (Decimal-safe,
            never float). A value object has no neutral zero, so an EMPTY collection raises a
            domain error rather than fabricating one (mirrors the C#/TS empty-fold guard).
            """
            it = iter(values)
            try:
                total = next(it)
            except StopIteration:
                raise DomainInvariantViolationError(
                    "collection", "cannot sum an empty collection (no zero value)"
                ) from None
            for value in it:
                total = total + value
            return total
        """";

    /// <summary>
    /// The full source of the shared infrastructure-runtime module (issue #241). Dependency-free (stdlib
    /// only), fully annotated, <c>mypy --strict</c>-clean. Emitted once, only when the Infrastructure
    /// layer is requested. Holds the persistence seam (<c>AggregateStore</c> + <c>InMemoryStore</c>), the
    /// transactional-outbox primitives (<c>OutboxMessage</c>, <c>OutboxStore</c>, <c>InMemoryOutboxStore</c>,
    /// <c>IntegrationEventHandler</c>), and the command-pipeline primitives (<c>PipelineBehavior</c>,
    /// <c>Validator</c>, <c>ValidationError</c>).
    /// </summary>
    public const string InfrastructureSource =
        """"
        # <auto-generated/>
        # Koine Python infrastructure runtime: shared, dependency-free persistence, outbox and
        # command-pipeline primitives, emitted once when --layers infrastructure is set.
        from __future__ import annotations

        import json
        import uuid
        from collections.abc import Awaitable, Callable, Hashable, Sequence
        from datetime import datetime
        from typing import Generic, Protocol, TypeVar

        from koine_runtime import Instant

        TId = TypeVar("TId", bound=Hashable, contravariant=True)
        TEntity = TypeVar("TEntity")
        TRequest = TypeVar("TRequest", contravariant=True)
        TResponse = TypeVar("TResponse")


        class AggregateStore(Protocol[TId, TEntity]):
            """The persistence port over an aggregate root identified by `TId`.

            The generated `<Root>RepositoryImpl` is written against this protocol, never a concrete
            store — drop in a database-backed `AggregateStore` to make the generated stack persistent.
            The default (`InMemoryStore`) keeps aggregates in a dict and is runnable in tests.
            """

            async def get(self, id: TId) -> TEntity | None: ...
            async def all(self) -> tuple[TEntity, ...]: ...
            async def add(self, entity: TEntity) -> None: ...
            async def update(self, entity: TEntity) -> None: ...
            async def remove(self, entity: TEntity) -> None: ...


        class InMemoryStore(Generic[TId, TEntity]):
            """The zero-dependency in-memory `AggregateStore`: aggregates live in a dict keyed by their
            (hashable) identity. The runnable default and a test double — NOT a production datastore.
            """

            def __init__(self, identify: Callable[[TEntity], TId]) -> None:
                self._identify = identify
                self._entities: dict[TId, TEntity] = {}

            async def get(self, id: TId) -> TEntity | None:
                return self._entities.get(id)

            async def all(self) -> tuple[TEntity, ...]:
                return tuple(self._entities.values())

            async def add(self, entity: TEntity) -> None:
                self._entities[self._identify(entity)] = entity

            async def update(self, entity: TEntity) -> None:
                self._entities[self._identify(entity)] = entity

            async def remove(self, entity: TEntity) -> None:
                self._entities.pop(self._identify(entity), None)


        class OutboxMessage:
            """A persisted, serialized integration event awaiting dispatch (the transactional-outbox row).

            Written in the same `save_changes` as the aggregate change so an event is never lost on
            commit; `processed_on` is stamped once the dispatcher has delivered it.
            """

            id: str
            type: str
            payload: str
            occurred_on: datetime
            processed_on: datetime | None

            def __init__(self, type: str, payload: str, occurred_on: datetime | None = None) -> None:
                self.id = uuid.uuid4().hex
                self.type = type
                self.payload = payload
                self.occurred_on = occurred_on if occurred_on is not None else Instant.now()
                self.processed_on = None

            @staticmethod
            def of(integration_event: object) -> OutboxMessage:
                """Serializes an integration event into an opaque outbox row (type name + JSON payload)."""
                payload = json.dumps(getattr(integration_event, "__dict__", {}), default=str, sort_keys=True)
                return OutboxMessage(type(integration_event).__name__, payload)


        class OutboxStore(Protocol):
            """The persistence port for outbox rows; `InMemoryOutboxStore` is the runnable default."""

            async def add(self, message: OutboxMessage) -> None: ...
            async def unprocessed(self) -> tuple[OutboxMessage, ...]: ...
            async def mark_processed(self, message: OutboxMessage) -> None: ...


        class InMemoryOutboxStore:
            """The zero-dependency in-memory `OutboxStore`: rows live in a list, ordered by insertion."""

            def __init__(self) -> None:
                self._messages: list[OutboxMessage] = []

            async def add(self, message: OutboxMessage) -> None:
                self._messages.append(message)

            async def unprocessed(self) -> tuple[OutboxMessage, ...]:
                return tuple(m for m in self._messages if m.processed_on is None)

            async def mark_processed(self, message: OutboxMessage) -> None:
                message.processed_on = Instant.now()


        class IntegrationEventHandler(Protocol):
            """Delivers a drained integration event (its outbox row) to its in-process subscribers.

            The publisher stays decoupled from its subscribers: the consumer implements this single
            seam to fan out to their handlers.
            """

            async def handle(self, message: OutboxMessage) -> None: ...


        class Validator(Protocol[TRequest]):
            """A request validator: returns the validation errors for a request (empty when valid)."""

            def validate(self, request: TRequest) -> Sequence[str]: ...


        class ValidationError(Exception):
            """Raised by the validation behavior when a request fails one or more validators."""

            errors: tuple[str, ...]

            def __init__(self, errors: Sequence[str]) -> None:
                super().__init__("Validation failed: " + "; ".join(errors))
                self.errors = tuple(errors)


        # A command-pipeline behavior: receives the request and a `next` continuation returning the
        # response, and either short-circuits or delegates to `next`. The MediatR-style behavior the C#
        # emitter renders as `IPipelineBehavior`, expressed idiomatically as a callable alias.
        PipelineBehavior = Callable[[TRequest, Callable[[], Awaitable[TResponse]]], Awaitable[TResponse]]
        """";
}
