namespace Koine.Compiler.Emit.Python;

/// <summary>
/// The once-emitted Python runtime support, the analogue of the C# emitter's <c>Koine.Runtime</c>
/// files and the TypeScript emitter's <c>runtime.ts</c>. It is written to a single
/// <c>koine_runtime.py</c> at the output root and provides the shared domain primitives every
/// generated module imports:
/// <list type="bullet">
/// <item><c>DomainInvariantViolationError</c> — raised when an invariant or illegal state
/// transition fails (carries the offending type name and rule).</item>
/// <item><c>ConcurrencyConflictError</c> — raised on an optimistic-concurrency version mismatch.</item>
/// <item><c>Instant</c> — a helper exposing <c>now()</c> → a timezone-aware UTC <c>datetime</c>.</item>
/// <item><c>Range[T]</c> — a closed interval over an orderable type, with containment/overlap.</item>
/// <item><c>AggregateRoot</c>/<c>QueryHandler</c> — structural <c>Protocol</c>s.</item>
/// </list>
/// The contents are a fixed string constant (no per-model state), so emission is deterministic and
/// byte-identical across runs. The module is dependency-free (stdlib only) and <c>mypy --strict</c>-clean.
/// </summary>
internal static class PyRuntime
{
    /// <summary>The emitted runtime file path, at the output root.</summary>
    public const string FileName = "koine_runtime.py";

    /// <summary>The dotted import name of the runtime module (<c>from koine_runtime import …</c>).</summary>
    public const string ModuleName = "koine_runtime";

    /// <summary>The full source of the runtime module.</summary>
    public const string Source =
        """"
        # <auto-generated/>
        # Koine Python runtime: shared domain primitives, emitted once.
        from __future__ import annotations

        from datetime import datetime, timezone
        from decimal import Decimal
        from typing import Any, Callable, Generic, Iterable, Protocol, TypeVar, runtime_checkable


        class DomainInvariantViolationError(Exception):
            """Raised when a domain invariant or illegal state transition is violated."""

            type_name: str
            rule: str

            def __init__(self, type_name: str, rule: str) -> None:
                super().__init__(f"Invariant violated on {type_name}: {rule}")
                self.type_name = type_name
                self.rule = rule


        class ConcurrencyConflictError(Exception):
            """Raised when an optimistic-concurrency version check fails on a versioned aggregate."""

            type_name: str
            expected: int
            actual: int

            def __init__(self, type_name: str, expected: int, actual: int) -> None:
                super().__init__(
                    f"Concurrency conflict on {type_name}: expected version {expected}, was {actual}"
                )
                self.type_name = type_name
                self.expected = expected
                self.actual = actual


        class Instant:
            """Time source for `now`-typed defaults: a timezone-aware UTC instant."""

            @staticmethod
            def now() -> datetime:
                """The current instant, as a timezone-aware UTC `datetime`."""
                return datetime.now(timezone.utc)


        class _Comparable(Protocol):
            """An element type orderable via `<` / `<=` (the default `Range` ordering).

            The comparison parameter is typed `Any` (not `object`) so a stdlib orderable such as
            `datetime` — whose `__lt__`/`__le__` accept only their own type, not arbitrary `object`
            — structurally satisfies the protocol (the typeshed `SupportsRichComparison` approach).
            """

            def __lt__(self, other: Any) -> bool: ...

            def __le__(self, other: Any) -> bool: ...


        T = TypeVar("T", bound=_Comparable)


        class Range(Generic[T]):
            """A closed interval [start, end] over an orderable type, with containment and overlap.

            Ordering defaults to the element type's `<=`; an explicit `compare` callable (returning
            a negative/zero/positive int, like `functools.cmp_to_key`) may be supplied for element
            types that are not directly orderable.
            """

            start: T
            end: T

            def __init__(
                self, start: T, end: T, compare: Callable[[T, T], int] | None = None
            ) -> None:
                self._compare = compare
                if self._cmp(start, end) > 0:
                    raise DomainInvariantViolationError(
                        "Range", "start must be less than or equal to end"
                    )
                self.start = start
                self.end = end

            def _cmp(self, a: T, b: T) -> int:
                if self._compare is not None:
                    return self._compare(a, b)
                if a < b:
                    return -1
                if b < a:
                    return 1
                return 0

            def contains(self, value: T) -> bool:
                """True when `value` lies within [start, end] inclusive."""
                return self._cmp(value, self.start) >= 0 and self._cmp(value, self.end) <= 0

            def overlaps(self, other: Range[T]) -> bool:
                """True when this range shares at least one point with `other`."""
                return self._cmp(self.start, other.end) <= 0 and self._cmp(other.start, self.end) <= 0

            def __eq__(self, other: object) -> bool:
                if not isinstance(other, Range):
                    return NotImplemented
                return bool(self.start == other.start and self.end == other.end)

            def __hash__(self) -> int:
                return hash((self.start, self.end))


        @runtime_checkable
        class AggregateRoot(Protocol):
            """The marker every aggregate root satisfies: it exposes its identity."""

            @property
            def id(self) -> object: ...


        TQuery = TypeVar("TQuery", contravariant=True)
        TResult = TypeVar("TResult", covariant=True)


        @runtime_checkable
        class QueryHandler(Protocol[TQuery, TResult]):
            """Handles a read-side query, returning its result (the CQRS query seam)."""

            def handle(self, query: TQuery) -> TResult: ...


        TFold = TypeVar("TFold", bound=_Comparable)


        def koine_min(values: Iterable[TFold]) -> TFold:
            """The minimum element, raising a domain error on an empty collection (no value)."""
            it = iter(values)
            try:
                result = next(it)
            except StopIteration:
                raise DomainInvariantViolationError(
                    "collection", "cannot take min of an empty collection (no value)"
                ) from None
            for value in it:
                if value < result:
                    result = value
            return result


        def koine_max(values: Iterable[TFold]) -> TFold:
            """The maximum element, raising a domain error on an empty collection (no value)."""
            it = iter(values)
            try:
                result = next(it)
            except StopIteration:
                raise DomainInvariantViolationError(
                    "collection", "cannot take max of an empty collection (no value)"
                ) from None
            for value in it:
                if result < value:
                    result = value
            return result


        def koine_sum(values: Iterable[Decimal]) -> Decimal:
            """The Decimal-safe sum of a collection (never float); empty sums to Decimal zero."""
            total = Decimal(0)
            for value in values:
                total += value
            return total
        """";
}
