using Koine.Compiler.Ast;
using Koine.Compiler.Emit.CSharp;

namespace Koine.Compiler.Emit.Python;

/// <summary>
/// The Python backend. Turns a validated <see cref="KoineModel"/> into idiomatic,
/// <c>mypy --strict</c>-clean Python that preserves Koine's domain semantics. Modeled on the
/// TypeScript backend: one module per type, DDD subfolders (<c>value_objects/</c>, <c>entities/</c>,
/// <c>enums/</c>, <c>events/</c>, <c>repositories/</c>), and a fixed-string runtime emitted once at
/// the output root.
/// <para>
/// Value objects (and quantities) emit as frozen dataclasses (Task 5). Entities, enums, aggregates,
/// events, and repositories are dispatched through <see cref="EmitType"/> and land in later tasks
/// (currently no-ops). All Python-specific decisions live in this folder; the AST stays agnostic.
/// </para>
/// </summary>
public sealed partial class PythonEmitter : IEmitter
{
    // Options influence package remapping (and, in a later phase, optional dict-helper generation).
    private readonly PythonEmitterOptions _options;

    /// <summary>Creates a <see cref="PythonEmitter"/> with default options
    /// (<see cref="PythonEmitterOptions.Empty"/>).</summary>
    public PythonEmitter() : this(PythonEmitterOptions.Empty) { }

    /// <summary>Creates a <see cref="PythonEmitter"/> with the supplied options.</summary>
    internal PythonEmitter(PythonEmitterOptions options)
    {
        _options = options;
    }

    public string TargetName => "python";

    private const string Indent = "    ";

    /// <summary>
    /// A strict <c>mypy.ini</c> pinned to the supported Python floor (3.11). The emitted tree is
    /// checked AS SHIPPED: dependency-free, fully annotated, and strict-clean.
    /// </summary>
    private const string MypyIni =
        "# <auto-generated/>\n" +
        "[mypy]\n" +
        "python_version = 3.11\n" +
        "strict = True\n";

    /// <summary>The PEP 561 marker that flags the generated package as typed.</summary>
    private const string PyTyped = "";

    /// <summary>A minimal, build-backend-agnostic <c>pyproject.toml</c> for the generated package.</summary>
    private const string PyProjectToml =
        "# <auto-generated/>\n" +
        "[project]\n" +
        "name = \"koine-generated\"\n" +
        "version = \"0.0.0\"\n" +
        "description = \"Generated by Koine — do not edit by hand.\"\n" +
        "requires-python = \">=3.11\"\n";

    public IReadOnlyList<EmittedFile> Emit(KoineModel model) => Emit(model, null);

    public IReadOnlyList<EmittedFile> Emit(KoineModel model, SemanticModel? semantic)
    {
        ModelIndex index = (semantic ?? new SemanticModel(model)).Index;
        var typeMapper = new PythonTypeMapper(index);

        var emit = new PyEmitContext(
            index,
            BuildEnumMemberMap(model),
            BuildTypeLocations(model),
            model.Contexts.Select(c => c.Name).ToList(),
            // Demand-driven operator emission (R9): a value object only gets an additive `__add__`
            // (where the model `sum`s it) or a scalar `__mul__` (where the model multiplies it by a
            // scalar) — shared with the C#/TS emitters so the three stay semantically aligned.
            OperatorNeedsAnalyzer.BuildAdditiveOperatorNeeds(model, index),
            OperatorNeedsAnalyzer.BuildScalarOperatorNeeds(model, index));

        var files = new List<EmittedFile>();

        // 1. Runtime support and the project-root files, emitted once at the output root.
        files.Add(new EmittedFile(PyRuntime.FileName, PyRuntime.Source + "\n"));
        files.Add(new EmittedFile("mypy.ini", MypyIni));
        files.Add(new EmittedFile("py.typed", PyTyped));
        files.Add(new EmittedFile("pyproject.toml", PyProjectToml));

        // 2. Per-context user types, one module each.
        foreach (ContextNode ctx in model.Contexts)
        {
            foreach (TypeDecl type in ctx.AllTypeDecls())
            {
                var ns = ModelIndex.NamespaceOf(ctx.Name, type.ModulePath);
                EmitType(emit, files, type, ns, typeMapper);
            }

            // ID types referenced but not owned by an entity in this context (e.g. a foreign *Id):
            // materialize a standalone branded-guid identity at the context package root so a
            // cross-context reference resolves to a real module. Deterministic (sorted).
            foreach (var idName in OrderedUnownedIds(ctx, index))
            {
                files.Add(EmitIdType(emit, idName, ctx.Name, IdentityStrategy.Guid, null));
            }
        }

        // 3. An `__init__.py` for every package directory implied by the emitted module paths, so the
        //    tree imports cleanly and mypy treats each directory as a package.
        EmitPackageInits(files);

        return files;
    }

    /// <summary>
    /// Dispatches a single <see cref="TypeDecl"/> to its construct emitter. Value objects (regular
    /// and quantities) and smart enums emit now; entities, aggregates, and events are no-ops until
    /// their later tasks.
    /// </summary>
    private void EmitType(PyEmitContext emit, List<EmittedFile> files, TypeDecl type, string ns, PythonTypeMapper typeMapper)
    {
        // `AllTypeDecls()` already flattens each aggregate's nested types into the iteration, so an
        // `AggregateDecl` itself is a no-op here (its entity/events arrive as their own decls); only
        // the leaf constructs are routed.
        switch (type)
        {
            // A `quantity` and a regular `value` share one emitter; the quantity flag inside
            // `EmitValueObject` routes the unit-checked dunder ops. A quantity's unit member is
            // enum-typed (R9.2 / KOI0904), and enums now emit, so the cross-module enum import
            // resolves.
            case ValueObjectDecl vo:
                files.Add(EmitValueObject(emit, vo, ns, typeMapper));
                break;
            case EnumDecl @enum:
                files.Add(EmitEnum(emit, @enum, ns, typeMapper));
                break;
            // An entity emits as a mutable @dataclass(eq=False) with identity equality, plus its
            // branded `<XId>` value object (per ID strategy). Its commands/factories/state machines
            // land in Task 8; aggregate-root placement (context-root module) lands in Task 9, so for
            // now every entity — including an aggregate root — emits into `entities/`.
            case EntityDecl entity:
                files.Add(EmitEntity(emit, entity, ns, typeMapper));
                files.Add(EmitIdType(emit, entity.IdentityName, ns, entity.IdStrategy, entity.IdBackingType));
                break;
            case EventDecl:
            case AggregateDecl:
                // Filled in by later tasks (events, aggregates/repositories).
                break;
        }
    }
}
