using System.Text;
using Koine.Compiler.Ast;
using Koine.Compiler.Emit;

namespace Koine.Compiler;

/// <summary>
/// Orchestration support for <see cref="KotlinEmitter"/>: the per-emit state threaded through the construct
/// emitters, the per-context package computation, the source-path layout, and the file header/assemble step
/// every construct emitter shares (each emits one top-level type per <c>.kt</c> file). The Kotlin analogue of
/// the Java backend's <c>JavaEmitter.Support.cs</c> — a package per bounded context
/// (<c>&lt;base&gt;.&lt;context&gt;</c>) mapped to a directory tree, and — because JDK / runtime types are
/// referenced fully qualified and Kotlin's own <c>List</c>/<c>Set</c>/<c>Map</c> are auto-imported — a header
/// with no <c>import</c> bookkeeping at all, so the output always compiles. Later tasks (events,
/// repositories, context extras) extend this file rather than duplicate the plumbing.
/// </summary>
public sealed partial class KotlinEmitter
{
    /// <summary>The four-space unit of Kotlin indentation used throughout the construct emitters.</summary>
    internal const string Indent = "    ";

    /// <summary>
    /// The immutable per-emit state threaded through every construct emitter. Carries the model index, the
    /// demand-driven value-object operator needs (which VOs need a <c>plus</c> from a <c>sum</c> fold or a
    /// plain <c>+</c>/<c>-</c>, which scalar types each is multiplied / divided by) so the value-object slice
    /// emits only the arithmetic operators the model actually uses, and an enum-member → owning-enum map that
    /// disambiguates a bare reference to a member shared across enums.
    /// </summary>
    internal sealed record KotlinEmitContext(
        ModelIndex Index,
        IReadOnlySet<string> AdditiveNeeds,
        IReadOnlyDictionary<string, IReadOnlySet<string>> ScalarNeeds,
        IReadOnlyDictionary<string, IReadOnlySet<string>> ScalarDivNeeds,
        IReadOnlyDictionary<string, IReadOnlySet<BinaryOp>> BinaryNeeds,
        IReadOnlyDictionary<string, string> EnumMemberToType);

    // ----------------------------------------------------------------------
    // Package / path / file assembly
    // ----------------------------------------------------------------------

    /// <summary>
    /// The Kotlin package a bounded context's types live in: the configured remap for the (lowercased)
    /// context name if one is present, else <c>&lt;base&gt;.&lt;context&gt;</c> (e.g. base
    /// <c>koine.generated</c> + context <c>Billing</c> → <c>koine.generated.billing</c>).
    /// </summary>
    private string PackageFor(string context) =>
        _options.PackageMap.TryGetValue(context.ToLowerInvariant(), out var mapped)
            ? mapped
            : $"{_options.BasePackage}.{KotlinNaming.ToPackageSegment(context)}";

    /// <summary>
    /// The source path for a top-level type: the package's dot segments become directories and the Kotlin
    /// type name is the file stem (e.g. package <c>koine.generated.billing</c> + type <c>Money</c> →
    /// <c>koine/generated/billing/Money.kt</c>). <paramref name="kotlinTypeName"/> is the already-cased Kotlin
    /// type name, so it matches the top-level type declared inside.
    /// </summary>
    private static string FilePathFor(string package, string kotlinTypeName) =>
        package.Replace('.', '/') + "/" + kotlinTypeName + ".kt";

    /// <summary>
    /// Wraps a rendered type body in its file header — the <c>// &lt;auto-generated/&gt;</c> banner and the
    /// <c>package</c> declaration (no semicolon) — and guarantees a trailing newline. No <c>import</c> lines
    /// are needed: JDK types (<see cref="KotlinTypeMapper"/>) and the runtime <c>koine.runtime.*</c> are
    /// referenced fully qualified, and Kotlin's collection types are auto-imported. The extension point later
    /// tasks reuse for every construct they emit.
    /// </summary>
    private static string Assemble(string package, string body)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("package ").Append(package).Append("\n\n");
        sb.Append(body);
        if (!body.EndsWith('\n'))
        {
            sb.Append('\n');
        }

        return sb.ToString();
    }

    /// <summary>
    /// Assembles a single per-type Kotlin source file for <paramref name="context"/>: computes the package, the
    /// file path, and prepends the header/package to <paramref name="body"/>. Every construct emitter funnels
    /// through here so the layout stays uniform across value objects, enums, entities, and events.
    /// </summary>
    private EmittedFile TypeFile(string context, string kotlinTypeName, string body)
    {
        var package = PackageFor(context);
        return new EmittedFile(FilePathFor(package, kotlinTypeName), Assemble(package, body));
    }

    // ----------------------------------------------------------------------
    // Shared formatting helpers
    // ----------------------------------------------------------------------

    /// <summary>Renders a target-agnostic doc string as a Kotlin <c>/** … */</c> KDoc block at <paramref name="indent"/> (a no-op when empty).</summary>
    internal static void WriteKdoc(StringBuilder sb, string? doc, string indent)
    {
        if (string.IsNullOrEmpty(doc))
        {
            return;
        }

        sb.Append(indent).Append("/**\n");
        foreach (var line in doc.Split('\n'))
        {
            sb.Append(indent).Append(" *");
            if (line.Length > 0)
            {
                sb.Append(' ').Append(line);
            }

            sb.Append('\n');
        }

        sb.Append(indent).Append(" */\n");
    }

    /// <summary>Renders <paramref name="raw"/> as a Kotlin double-quoted string literal (escaping backslash, quote, <c>$</c>, and the C0 whitespace escapes).</summary>
    internal static string KotlinStringLiteral(string raw)
    {
        var sb = new StringBuilder(raw.Length + 2);
        sb.Append('"');
        foreach (var c in raw)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '$': sb.Append("\\$"); break; // Kotlin string templates: `$` must be escaped in a literal.
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }

    /// <summary>
    /// Builds the enum-member → owning-enum-type map: a member name maps to its enum only when exactly one
    /// enum in the model declares it, so the expression translator can qualify a bare member reference
    /// (<c>Draft</c> → <c>OrderStatus.Draft</c>) without ambiguity. Members shared across two enums are left
    /// out (the translator falls back to the field-type hint).
    /// </summary>
    private static IReadOnlyDictionary<string, string> BuildEnumMemberMap(KoineModel model)
    {
        var owners = new Dictionary<string, string?>(StringComparer.Ordinal);
        foreach (EnumDecl e in model.Contexts.SelectMany(c => c.AllTypeDecls()).OfType<EnumDecl>())
        {
            foreach (EnumMember m in e.Members)
            {
                owners[m.Name] = owners.ContainsKey(m.Name) ? null : e.Name;
            }
        }

        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var (member, owner) in owners)
        {
            if (owner is not null)
            {
                map[member] = owner;
            }
        }

        return map;
    }
}
