namespace Koine.Compiler;

/// <summary>
/// The fixed-string runtime for the generated Kotlin sources, emitted once into the shared
/// <c>koine.runtime</c> package (the Kotlin analogue of <see cref="JavaRuntime"/> / <see cref="RustRuntime"/>).
/// Phase 1 supplies the shared symbols the emitted types reference: <c>DomainException</c>, an unchecked
/// exception thrown when a domain invariant is violated (parallel to the C# emitter's
/// <c>DomainInvariantViolationException</c> and the JVM sibling's <c>koine.runtime.DomainException</c>), and
/// <c>Range&lt;T&gt;</c>, the closed-interval value type a Koine <c>Range&lt;T&gt;</c> field maps to.
/// Dependency-free — Kotlin stdlib + JDK only, no Arrow/kotlinx.
/// <para>
/// Unlike the Java backend (one public type per file), the runtime is a single hand-written
/// <c>Runtime.kt</c>: Kotlin imposes no one-type-per-file rule, so co-locating the two support types keeps
/// the runtime package a single, reviewable file. Generated invariants throw <c>DomainException</c> inline
/// (<c>if (…) throw koine.runtime.DomainException(msg)</c>), so no <c>require</c>-style guard helper is
/// needed — matching the JVM sibling's proven shape.
/// </para>
/// </summary>
internal static class KotlinRuntime
{
    /// <summary>The <c>koine.runtime</c> package the generated types reference shared support from.</summary>
    public const string Package = "koine.runtime";

    /// <summary>The path of the emitted runtime source (the shared <c>koine.runtime</c> package, one file).</summary>
    public const string FileName = "koine/runtime/Runtime.kt";

    /// <summary>
    /// The <c>koine.runtime</c> source (no trailing newline; the emitter adds one). <c>DomainException</c> is
    /// a <c>RuntimeException</c> (all Kotlin exceptions are unchecked) so smart constructors and
    /// invariant-guarded behaviors can signal a broken invariant without ceremony, matching how the C#/Java/Rust
    /// backends model failure. <c>Range&lt;T&gt;</c> is a closed interval <c>[start, end]</c> over a
    /// <c>Comparable</c> type — the Kotlin analogue of the JVM sibling's runtime <c>Range</c> — with
    /// <c>contains</c>/<c>overlaps</c> tests; the caller owns the <c>start &lt;= end</c> invariant.
    /// </summary>
    public const string Source =
        """
        // <auto-generated/>
        package koine.runtime

        /**
         * Thrown when a domain invariant is violated. An unchecked exception (every Kotlin exception is
         * unchecked) so generated value objects, entities, and aggregates can guard their invariants without
         * ceremony — the Kotlin analogue of the C# emitter's DomainInvariantViolationException and the JVM
         * sibling's koine.runtime.DomainException.
         *
         * Generated by Koine — do not edit by hand.
         */
        class DomainException(message: String) : RuntimeException(message)

        /**
         * A closed interval [start, end] over a Comparable type — the Kotlin analogue of the JVM sibling's
         * koine.runtime.Range. The caller is responsible for start <= end (a domain invariant).
         *
         * Generated by Koine — do not edit by hand.
         */
        data class Range<T : Comparable<T>>(val start: T, val end: T) {
            /** True when [value] lies within the closed interval [start, end]. */
            fun contains(value: T): Boolean = start <= value && value <= end

            /** True when this interval and [other] share at least one point. */
            fun overlaps(other: Range<T>): Boolean = start <= other.end && other.start <= end
        }
        """;
}
