using System.Text;
using Koine.Compiler.Ast;

namespace Koine.Compiler.Emit.Python;

/// <summary>
/// The opt-in Infrastructure layer of <see cref="PythonEmitter"/> (issue #241), the Python analogue of
/// the C# emitter's <c>--layers infrastructure</c> output. Emitted only when
/// <see cref="PythonEmitterOptions.EmitsInfrastructure"/> is set, it realizes — dependency-free and
/// <c>mypy --strict</c>-clean — the persistence-ignorant contracts the domain layer already produces:
/// concrete repository implementations over an injectable <c>AggregateStore</c> (in-memory by default), a
/// concrete unit of work, a transactional outbox + dispatcher (publishing contexts only),
/// validation/transaction pipeline behaviors, and a provider/composition helper.
///
/// <para>All infrastructure decisions live in this folder — <c>Ast/</c> stays target-agnostic. Every
/// module is deterministic (declaration order) and ends in a single trailing newline, like the rest of
/// the emitter. The layer is off by default, so the domain output is byte-identical to today.</para>
/// </summary>
public sealed partial class PythonEmitter
{
    /// <summary>
    /// Emits the Infrastructure layer for every bounded context that has at least one aggregate whose
    /// root is an entity (the same gate as the repository emission). A context with no such aggregate
    /// produces no infrastructure — and a model with none produces nothing extra, no error. The shared
    /// <c>koine_infrastructure</c> module is emitted once.
    /// </summary>
    private void EmitInfrastructure(PyEmitContext emit, KoineModel model, List<EmittedFile> files, PythonTypeMapper typeMapper)
    {
        var anyEmitted = false;
        foreach (ContextNode ctx in model.Contexts)
        {
            var aggregates = ctx.Types.OfType<AggregateDecl>()
                .Where(a => a.RootEntity() is not null)
                .ToList();
            if (aggregates.Count == 0)
            {
                continue;
            }

            anyEmitted = true;
            var publishesEvents = ctx.Publishes.Count > 0;

            foreach (AggregateDecl agg in aggregates)
            {
                files.Add(EmitRepositoryImpl(emit, ctx.Name, agg, typeMapper));
            }

            files.Add(EmitUnitOfWorkImpl(ctx.Name, aggregates, publishesEvents));

            if (publishesEvents)
            {
                files.Add(EmitIntegrationEventDispatcher(ctx.Name));
            }

            files.Add(EmitBehaviors(ctx.Name));
            files.Add(EmitProvider(ctx.Name, aggregates, publishesEvents));
        }

        if (anyEmitted)
        {
            files.Add(new EmittedFile(PyRuntime.InfrastructureFileName, PyRuntime.InfrastructureSource + "\n"));
        }
    }

    /// <summary>A small English pluralizer for unit-of-work repository attribute names (Order → Orders, Category → Categories).</summary>
    private static string Pluralize(string name)
    {
        if (name.Length == 0)
        {
            return name;
        }

        if (name.EndsWith("s", StringComparison.Ordinal) || name.EndsWith("x", StringComparison.Ordinal)
            || name.EndsWith("z", StringComparison.Ordinal) || name.EndsWith("ch", StringComparison.Ordinal)
            || name.EndsWith("sh", StringComparison.Ordinal))
        {
            return name + "es";
        }

        if (name.Length >= 2 && char.ToLowerInvariant(name[^1]) == 'y'
            && "aeiou".IndexOf(char.ToLowerInvariant(name[^2])) < 0)
        {
            return name[..^1] + "ies";
        }

        return name + "s";
    }

    /// <summary>The dotted import module the shared <c>koine_infrastructure</c> symbols are reached at.</summary>
    private const string InfraModule = "koine_infrastructure";

    /// <summary>The dotted import module a context's infrastructure type is emitted at.</summary>
    private string InfraModuleDotted(string contextName, string typeName) =>
        ModuleDottedFor(contextName, KindFolder.Infrastructure, typeName);

    /// <summary>
    /// Wraps a rendered infrastructure module body with its <c># &lt;auto-generated/&gt;</c> banner,
    /// the <c>from __future__ import annotations</c> line, the supplied stdlib lines (sorted), and the
    /// supplied cross-module imports (grouped by module, modules sorted, symbols sorted) — fully
    /// deterministic, mirroring the import layout of the main <see cref="Assemble"/>.
    /// </summary>
    private static string RenderPyInfra(string body, IReadOnlyList<string> stdlib, IReadOnlyList<(string Module, string Symbol)> imports)
    {
        var sb = new StringBuilder();
        sb.Append("# <auto-generated/>\n");
        sb.Append("from __future__ import annotations\n");

        foreach (var line in stdlib.Distinct(StringComparer.Ordinal).OrderBy(s => s, StringComparer.Ordinal))
        {
            sb.Append(line).Append('\n');
        }

        foreach (var group in imports.GroupBy(i => i.Module).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var symbols = group.Select(i => i.Symbol).Distinct(StringComparer.Ordinal).OrderBy(s => s, StringComparer.Ordinal);
            sb.Append("from ").Append(group.Key).Append(" import ").Append(string.Join(", ", symbols)).Append('\n');
        }

        sb.Append('\n').Append('\n');
        sb.Append(body);
        if (!body.EndsWith('\n'))
        {
            sb.Append('\n');
        }

        return sb.ToString();
    }

    /// <summary>
    /// The dotted module a user type symbol is emitted at, via the <see cref="PyTypeLocation"/> table,
    /// preferring a location in <paramref name="thisContext"/>. <c>null</c> when the symbol is not a known
    /// user type (a primitive/runtime name needs no cross-module import).
    /// </summary>
    private static string? ResolvePyModule(PyEmitContext emit, string thisContext, string symbol)
    {
        string? fallback = null;
        foreach (PyTypeLocation loc in emit.TypeLocations)
        {
            if (loc.ExportName != symbol)
            {
                continue;
            }

            if (loc.Context == thisContext)
            {
                return loc.ModuleDotted;
            }

            fallback ??= loc.ModuleDotted;
        }

        return fallback;
    }
}
