// Generates website/src/playground/samples/samples.generated.ts from the repo's top-level
// `templates/` directory — the single validated source of truth (issue #101).
//
// The playground is a SINGLE-FILE editor (it passes one .koi source string to the wasm compiler),
// so only starter templates whose folder contains exactly one .koi file are included (today:
// billing, ordering, contextmap, values).
//
// Reuses `collectTemplates` + `resolveTemplatesDir` from the studio's generator — zero duplication.
// Run via `npm run build:samples`; invoked automatically by predev/prebuild alongside the other
// build:* steps. Output is git-ignored and regenerated on every build.
//
// No deps beyond Node's stdlib (all heavy lifting in the imported generator).
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const websiteDir = resolve(here, '..');

// Import the pure core from the studio generator — not a copy, a real import.
const studioGeneratorPath = resolve(
  websiteDir,
  '..',
  'tooling',
  'koine-studio',
  'scripts',
  'generate-templates.mjs',
);
const { collectTemplates, resolveTemplatesDir } = await import(studioGeneratorPath);

const templatesDir = resolveTemplatesDir();
if (!existsSync(templatesDir)) {
  console.error(`ERROR: templates directory not found at ${templatesDir}.`);
  process.exit(1);
}

// Collect ALL templates then restrict to single-file starters: the playground compiles one .koi
// source string and does not support multi-file workspaces, so multi-file templates cannot be
// included safely (the second context or import would be missing).
const all = collectTemplates(templatesDir);
const samples = all.filter((t) => t.files.length === 1);

if (samples.length === 0) {
  console.error('ERROR: no single-file templates found — cannot generate playground samples.');
  process.exit(1);
}

// Render the generated TypeScript module.
const lines = [
  '// AUTO-GENERATED by scripts/build-samples.mjs from the repo `templates/` directory.',
  '// DO NOT EDIT BY HAND and DO NOT COMMIT — it is git-ignored and regenerated on dev/build.',
  '',
  "import type { Sample } from './index';",
  '',
  'export const GENERATED_SAMPLES: Sample[] = [',
];
for (const t of samples) {
  // Escape backticks and ${} inside the raw koi source for a template literal.
  const escaped = t.source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  lines.push(`  {`);
  lines.push(`    id: ${JSON.stringify(t.id)},`);
  lines.push(`    label: ${JSON.stringify(t.name)},`);
  lines.push(`    blurb: ${JSON.stringify(t.tagline)},`);
  lines.push(`    code: \`${escaped}\`,`);
  lines.push(`  },`);
}
lines.push('];', '');

const outDir = join(websiteDir, 'src', 'playground', 'samples');
mkdirSync(outDir, { recursive: true });
const outFile = join(outDir, 'samples.generated.ts');
writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log(
  `Generated ${relative(websiteDir, outFile)} with ${samples.length} sample(s) from ${templatesDir}`,
);
console.log(`  Samples: ${samples.map((s) => s.id).join(', ')}`);
