namespace Koine.Compiler;

/// <summary>
/// The fixed-string runtime for the generated Java sources, emitted once into the shared
/// <c>koine.runtime</c> package (the Java analogue of <see cref="RustRuntime"/> / <c>PyRuntime</c>).
/// Phase 1 supplies the shared symbols the emitted types reference: <see cref="DomainException"/>, an
/// unchecked exception thrown when a domain invariant is violated (parallel to the C# emitter's
/// <c>DomainInvariantViolationException</c>), and <see cref="Range"/>, the closed-interval value type a
/// Koine <c>Range&lt;T&gt;</c> field maps to. Dependency-free — stdlib only, no Lombok/vavr/Spring.
/// </summary>
internal static class JavaRuntime
{
    /// <summary>The <c>koine.runtime</c> package the generated types import shared support from.</summary>
    public const string Package = "koine.runtime";

    /// <summary>The path of the emitted <see cref="DomainException"/> source, one public type per file.</summary>
    public const string DomainExceptionFileName = "koine/runtime/DomainException.java";

    /// <summary>The path of the emitted <see cref="Range"/> source, one public type per file.</summary>
    public const string RangeFileName = "koine/runtime/Range.java";

    /// <summary>The path of the emitted <c>QueryHandler</c> source, one public type per file.</summary>
    public const string QueryHandlerFileName = "koine/runtime/QueryHandler.java";

    /// <summary>
    /// The <c>DomainException</c> source (no trailing newline; the emitter adds one). An unchecked
    /// <c>RuntimeException</c> so smart constructors and invariant-guarded behaviors can signal a broken
    /// invariant without checked-exception noise, matching how the C#/Rust backends model failure.
    /// </summary>
    public const string DomainExceptionSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * Thrown when a domain invariant is violated. Unchecked ({@code RuntimeException}) so generated
         * value objects, entities, and aggregates can guard their invariants without checked-exception
         * ceremony — the Java analogue of the C# emitter's DomainInvariantViolationException.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         */
        public class DomainException extends RuntimeException {
            public DomainException(String message) {
                super(message);
            }
        }
        """;

    /// <summary>
    /// The <c>Range&lt;T&gt;</c> source (no trailing newline; the emitter adds one). A closed interval
    /// <c>[start, end]</c> over a comparable type — the Java analogue of the Rust runtime's <c>Range</c> —
    /// with <c>contains</c>/<c>overlaps</c> tests; the <c>start()</c>/<c>end()</c> accessors are the
    /// record's own. A Koine <c>Range&lt;T&gt;</c> field maps to this type
    /// (<see cref="JavaTypeMapper"/>), so it is always emitted alongside <see cref="DomainException"/>.
    /// </summary>
    public const string RangeSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * A closed interval {@code [start, end]} over a comparable type — the Java analogue of the Rust
         * runtime's {@code Range}. The {@code start()}/{@code end()} accessors are the record's own; the
         * caller is responsible for {@code start <= end} (a domain invariant).
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         */
        public record Range<T extends Comparable<? super T>>(T start, T end) {
            /** True when {@code value} lies within the closed interval {@code [start, end]}. */
            public boolean contains(T value) {
                return start.compareTo(value) <= 0 && value.compareTo(end) <= 0;
            }

            /** True when this interval and {@code other} share at least one point. */
            public boolean overlaps(Range<T> other) {
                return start.compareTo(other.end) <= 0 && other.start.compareTo(end) <= 0;
            }
        }
        """;

    /// <summary>
    /// The generic <c>QueryHandler&lt;Q, R&gt;</c> seam (no trailing newline; the emitter adds one) — the
    /// Java analogue of the C# runtime's <c>IQueryHandler&lt;TQuery,TResult&gt;</c> and the Python
    /// runtime's <c>QueryHandler</c> <c>Protocol</c>. Each emitted <c>query</c> ships a
    /// <c>&lt;Q&gt;Handler</c> interface specializing it, so the consumer implements one named seam per
    /// query rather than a raw generic. Returns the result synchronously: a query is a read, and making
    /// the seam <c>CompletableFuture</c>-shaped would force every hand-written in-memory handler to wrap
    /// its answer — the application-service boundary is where Koine models asynchrony.
    /// <para>
    /// Emitted only when the model declares at least one query, so a query-free model's output is
    /// unchanged (unlike <see cref="DomainExceptionSource"/>/<see cref="RangeSource"/>, which any field
    /// type can demand).
    /// </para>
    /// </summary>
    public const string QueryHandlerSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * Handles a query object, returning its typed result — the seam each generated
         * {@code <Query>Handler} interface specializes.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         *
         * @param <Q> the query object type
         * @param <R> the query's result type
         */
        public interface QueryHandler<Q, R> {
            /** Answers {@code query}. */
            R handle(Q query);
        }
        """;
}
