namespace Koine.Compiler;

/// <summary>
/// The fixed-string runtime for the generated Java sources, emitted once into the shared
/// <c>koine.runtime</c> package (the Java analogue of <see cref="RustRuntime"/> / <c>PyRuntime</c>).
/// Phase 1 supplies the shared symbols the emitted types reference: <see cref="DomainException"/>, an
/// unchecked exception thrown when a domain invariant is violated (parallel to the C# emitter's
/// <c>DomainInvariantViolationException</c>), and <see cref="Range"/>, the closed-interval value type a
/// Koine <c>Range&lt;T&gt;</c> field maps to. Dependency-free — stdlib only, no Lombok/vavr/Spring.
/// </summary>
internal static class JavaRuntime
{
    /// <summary>The <c>koine.runtime</c> package the generated types import shared support from.</summary>
    public const string Package = "koine.runtime";

    /// <summary>The path of the emitted <see cref="DomainException"/> source, one public type per file.</summary>
    public const string DomainExceptionFileName = "koine/runtime/DomainException.java";

    /// <summary>The path of the emitted <see cref="Range"/> source, one public type per file.</summary>
    public const string RangeFileName = "koine/runtime/Range.java";

    /// <summary>The path of the emitted <c>QueryHandler</c> source, one public type per file.</summary>
    public const string QueryHandlerFileName = "koine/runtime/QueryHandler.java";

    /// <summary>
    /// The <c>DomainException</c> source (no trailing newline; the emitter adds one). An unchecked
    /// <c>RuntimeException</c> so smart constructors and invariant-guarded behaviors can signal a broken
    /// invariant without checked-exception noise, matching how the C#/Rust backends model failure.
    /// </summary>
    public const string DomainExceptionSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * Thrown when a domain invariant is violated. Unchecked ({@code RuntimeException}) so generated
         * value objects, entities, and aggregates can guard their invariants without checked-exception
         * ceremony — the Java analogue of the C# emitter's DomainInvariantViolationException.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         */
        public class DomainException extends RuntimeException {
            public DomainException(String message) {
                super(message);
            }
        }
        """;

    /// <summary>
    /// The <c>Range&lt;T&gt;</c> source (no trailing newline; the emitter adds one). A closed interval
    /// <c>[start, end]</c> over a comparable type — the Java analogue of the Rust runtime's <c>Range</c> —
    /// with <c>contains</c>/<c>overlaps</c> tests; the <c>start()</c>/<c>end()</c> accessors are the
    /// record's own. A Koine <c>Range&lt;T&gt;</c> field maps to this type
    /// (<see cref="JavaTypeMapper"/>), so it is always emitted alongside <see cref="DomainException"/>.
    /// </summary>
    public const string RangeSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * A closed interval {@code [start, end]} over a comparable type — the Java analogue of the Rust
         * runtime's {@code Range}. The {@code start()}/{@code end()} accessors are the record's own; the
         * caller is responsible for {@code start <= end} (a domain invariant).
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         */
        public record Range<T extends Comparable<? super T>>(T start, T end) {
            /** True when {@code value} lies within the closed interval {@code [start, end]}. */
            public boolean contains(T value) {
                return start.compareTo(value) <= 0 && value.compareTo(end) <= 0;
            }

            /** True when this interval and {@code other} share at least one point. */
            public boolean overlaps(Range<T> other) {
                return start.compareTo(other.end) <= 0 && other.start.compareTo(end) <= 0;
            }
        }
        """;

    /// <summary>
    /// The generic <c>QueryHandler&lt;Q, R&gt;</c> seam (no trailing newline; the emitter adds one) — the
    /// Java analogue of the C# runtime's <c>IQueryHandler&lt;TQuery,TResult&gt;</c> and the Python
    /// runtime's <c>QueryHandler</c> <c>Protocol</c>. Each emitted <c>query</c> ships a
    /// <c>&lt;Q&gt;Handler</c> interface specializing it, so the consumer implements one named seam per
    /// query rather than a raw generic. Returns the result synchronously: a query is a read, and making
    /// the seam <c>CompletableFuture</c>-shaped would force every hand-written in-memory handler to wrap
    /// its answer — the application-service boundary is where Koine models asynchrony.
    /// <para>
    /// Emitted only when the model declares at least one query, so a query-free model's output is
    /// unchanged (unlike <see cref="DomainExceptionSource"/>/<see cref="RangeSource"/>, which any field
    /// type can demand).
    /// </para>
    /// </summary>
    public const string QueryHandlerSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * Handles a query object, returning its typed result — the seam each generated
         * {@code <Query>Handler} interface specializes.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         *
         * @param <Q> the query object type
         * @param <R> the query's result type
         */
        public interface QueryHandler<Q, R> {
            /** Answers {@code query}. */
            R handle(Q query);
        }
        """;

    // ------------------------------------------------------------------
    // The opt-in Infrastructure layer's shared primitives (issue #241 / #1090).
    // Emitted only under `--layers infrastructure`, so a domain-only emit is unchanged.
    // ------------------------------------------------------------------

    /// <summary>The paths of the shared infrastructure runtime types, one public type per file.</summary>
    public const string AggregateStoreFileName = "koine/runtime/AggregateStore.java";

    /// <inheritdoc cref="AggregateStoreFileName"/>
    public const string InMemoryStoreFileName = "koine/runtime/InMemoryStore.java";

    /// <inheritdoc cref="AggregateStoreFileName"/>
    public const string OutboxMessageFileName = "koine/runtime/OutboxMessage.java";

    /// <inheritdoc cref="AggregateStoreFileName"/>
    public const string OutboxStoreFileName = "koine/runtime/OutboxStore.java";

    /// <inheritdoc cref="AggregateStoreFileName"/>
    public const string InMemoryOutboxStoreFileName = "koine/runtime/InMemoryOutboxStore.java";

    /// <inheritdoc cref="AggregateStoreFileName"/>
    public const string IntegrationEventHandlerFileName = "koine/runtime/IntegrationEventHandler.java";

    /// <summary>
    /// The persistence seam every generated in-memory repository sits on: swap the default
    /// <see cref="InMemoryStoreSource"/> for a datastore-backed implementation and the repository is
    /// unchanged. The Java analogue of the Python infrastructure layer's <c>AggregateStore</c> protocol.
    /// </summary>
    public const string AggregateStoreSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * The persistence seam a generated repository sits on. The default {@link InMemoryStore} makes a
         * repository runnable with no wiring; inject another implementation to back it with a real
         * datastore without touching the generated repository.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         *
         * @param <I> the aggregate root's identity type
         * @param <T> the aggregate root type
         */
        public interface AggregateStore<I, T> {
            /** The aggregate with this identity, if stored. */
            java.util.Optional<T> get(I id);

            /** Stores a new aggregate (replacing any with the same identity). */
            void add(T aggregate);

            /** Stores changes to an existing aggregate. */
            void update(T aggregate);

            /** Removes the aggregate with this identity, if present. */
            void remove(I id);

            /** Every stored aggregate, in insertion order, as an unmodifiable snapshot. */
            java.util.List<T> all();
        }
        """;

    /// <summary>
    /// The zero-dependency default store: a synchronized, insertion-ordered map keyed on the aggregate's
    /// own identity (supplied as a function so the store never reflects over the aggregate). Insertion
    /// order makes <c>all()</c> — and therefore every generated finder — deterministic.
    /// </summary>
    public const string InMemoryStoreSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * The zero-dependency default {@link AggregateStore}: a synchronized, insertion-ordered map keyed
         * on each aggregate's own identity. Insertion order makes {@code all()} — and so every generated
         * finder — deterministic. Runnable in tests out of the box.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         *
         * @param <I> the aggregate root's identity type
         * @param <T> the aggregate root type
         */
        public final class InMemoryStore<I, T> implements AggregateStore<I, T> {
            private final java.util.Map<I, T> items = new java.util.LinkedHashMap<>();
            private final java.util.function.Function<T, I> identity;

            /** Creates a store that reads each aggregate's identity with {@code identity}. */
            public InMemoryStore(java.util.function.Function<T, I> identity) {
                this.identity = identity;
            }

            @Override
            public synchronized java.util.Optional<T> get(I id) {
                return java.util.Optional.ofNullable(this.items.get(id));
            }

            @Override
            public synchronized void add(T aggregate) {
                this.items.put(this.identity.apply(aggregate), aggregate);
            }

            @Override
            public synchronized void update(T aggregate) {
                this.items.put(this.identity.apply(aggregate), aggregate);
            }

            @Override
            public synchronized void remove(I id) {
                this.items.remove(id);
            }

            @Override
            public synchronized java.util.List<T> all() {
                return java.util.List.copyOf(this.items.values());
            }
        }
        """;

    /// <summary>
    /// One row of the transactional outbox: an integration event captured with its identity, type name,
    /// and occurrence time, plus whether it has been delivered. Immutable — <c>markProcessed</c> returns a
    /// new row — so a store can swap it in without aliasing a caller's copy.
    /// </summary>
    public const string OutboxMessageSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * One row of the transactional outbox: an integration event captured with its identity, type name,
         * and occurrence time, plus whether it has been delivered. Immutable — {@link #markProcessed()}
         * returns a new row rather than mutating this one.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         */
        public record OutboxMessage(
                java.util.UUID id, String type, Object payload, java.time.Instant occurredOn, boolean processed) {
            /** Captures {@code integrationEvent} as a fresh, undelivered outbox row. */
            public static OutboxMessage of(Object integrationEvent) {
                return new OutboxMessage(
                        java.util.UUID.randomUUID(),
                        integrationEvent.getClass().getSimpleName(),
                        integrationEvent,
                        java.time.Instant.now(),
                        false);
            }

            /** This row, marked delivered. */
            public OutboxMessage markProcessed() {
                return new OutboxMessage(this.id, this.type, this.payload, this.occurredOn, true);
            }
        }
        """;

    /// <summary>The outbox persistence seam: append a row, read the undelivered ones in order, mark one delivered.</summary>
    public const string OutboxStoreSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * The transactional outbox's persistence seam. The producer appends a row inside its own
         * transaction; the generated {@code IntegrationEventDispatcher} drains the undelivered ones
         * out-of-band.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         */
        public interface OutboxStore {
            /** Appends a row. */
            void add(OutboxMessage message);

            /** The undelivered rows, in the order they were appended, as an unmodifiable snapshot. */
            java.util.List<OutboxMessage> unprocessed();

            /** Marks the row with {@code message}'s identity delivered. A no-op when it is not stored. */
            void markProcessed(OutboxMessage message);
        }
        """;

    /// <summary>The zero-dependency default outbox store — synchronized, append-ordered, runnable in tests.</summary>
    public const string InMemoryOutboxStoreSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * The zero-dependency default {@link OutboxStore}: a synchronized, append-ordered list. Runnable
         * in tests out of the box; swap in a datastore-backed implementation for production.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         */
        public final class InMemoryOutboxStore implements OutboxStore {
            private final java.util.List<OutboxMessage> messages = new java.util.ArrayList<>();

            @Override
            public synchronized void add(OutboxMessage message) {
                this.messages.add(message);
            }

            @Override
            public synchronized java.util.List<OutboxMessage> unprocessed() {
                return this.messages.stream().filter(m -> !m.processed()).toList();
            }

            @Override
            public synchronized void markProcessed(OutboxMessage message) {
                for (int i = 0; i < this.messages.size(); i++) {
                    if (this.messages.get(i).id().equals(message.id())) {
                        this.messages.set(i, this.messages.get(i).markProcessed());
                        return;
                    }
                }
            }
        }
        """;

    /// <summary>The single delivery seam the dispatcher hands each drained outbox row to.</summary>
    public const string IntegrationEventHandlerSource =
        """
        // <auto-generated/>
        package koine.runtime;

        /**
         * The delivery seam the generated {@code IntegrationEventDispatcher} hands each drained outbox row
         * to — publish it to a broker, POST it, or whatever the deployment calls for.
         *
         * <p>Generated by Koine — do not edit by hand.</p>
         */
        public interface IntegrationEventHandler {
            /** Delivers one outbox row. Throwing leaves the row undelivered, so it is retried. */
            void handle(OutboxMessage message);
        }
        """;
}
