using System.Text;
using Koine.Compiler.Ast;
using Koine.Compiler.Emit;

namespace Koine.Compiler;

/// <summary>
/// Orchestration support for <see cref="JavaEmitter"/>: the per-emit state threaded through the
/// construct emitters, the per-context package computation, the source-path layout, and the file
/// header/assemble step every construct emitter shares (each emits one public type per <c>.java</c>
/// file). The Java analogue of the Rust backend's <c>RustEmitter.Support.cs</c>, but laid out the Java
/// way: a package per bounded context (<c>&lt;base&gt;.&lt;context&gt;</c>) mapped to a directory
/// tree, and — because stdlib and runtime types are referenced fully qualified — a header with no
/// <c>import</c> bookkeeping at all, so the output always compiles. Later tasks (events, repositories)
/// extend this file rather than duplicate the plumbing.
/// </summary>
public sealed partial class JavaEmitter
{
    /// <summary>The four-space unit of Java indentation used throughout the construct emitters.</summary>
    internal const string Indent = "    ";

    /// <summary>The immutable per-emit state threaded through every construct emitter (extended by later tasks).</summary>
    internal sealed record JavaEmitContext(ModelIndex Index);

    // ----------------------------------------------------------------------
    // Package / path / file assembly
    // ----------------------------------------------------------------------

    /// <summary>
    /// The Java package a bounded context's types live in: the configured remap for the (lowercased)
    /// context name if one is present, else <c>&lt;base&gt;.&lt;context&gt;</c> (e.g. base
    /// <c>koine.generated</c> + context <c>Billing</c> → <c>koine.generated.billing</c>).
    /// </summary>
    private string PackageFor(string context) =>
        _options.PackageMap.TryGetValue(context.ToLowerInvariant(), out var mapped)
            ? mapped
            : $"{_options.BasePackage}.{JavaNaming.Package(context)}";

    /// <summary>
    /// The source path for a top-level type: the package's dot segments become directories and the Java
    /// type name is the file stem (e.g. package <c>koine.generated.billing</c> + type <c>Money</c> →
    /// <c>koine/generated/billing/Money.java</c>). <paramref name="javaTypeName"/> is the already-cased
    /// Java type name, so it matches the public type declared inside.
    /// </summary>
    private static string FilePathFor(string package, string javaTypeName) =>
        package.Replace('.', '/') + "/" + javaTypeName + ".java";

    /// <summary>
    /// Wraps a rendered type body in its file header — the <c>// &lt;auto-generated/&gt;</c> banner and the
    /// <c>package</c> declaration — and guarantees a trailing newline. No <c>import</c> lines are needed:
    /// stdlib types (<see cref="JavaTypeMapper"/>) and the runtime <c>koine.runtime.DomainException</c>
    /// are all referenced fully qualified, so the assembled file always compiles. The extension point
    /// later tasks reuse for every construct they emit.
    /// </summary>
    private static string Assemble(string package, string body)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("package ").Append(package).Append(";\n\n");
        sb.Append(body);
        if (!body.EndsWith('\n'))
        {
            sb.Append('\n');
        }

        return sb.ToString();
    }

    /// <summary>
    /// Assembles a single per-type Java source file for <paramref name="context"/>: computes the package,
    /// the file path, and prepends the header/package to <paramref name="body"/>. Every construct emitter
    /// funnels through here so the layout stays uniform across value objects, enums, entities, and events.
    /// </summary>
    private EmittedFile TypeFile(string context, string javaTypeName, string body)
    {
        var package = PackageFor(context);
        return new EmittedFile(FilePathFor(package, javaTypeName), Assemble(package, body));
    }

    // ----------------------------------------------------------------------
    // Shared formatting helpers
    // ----------------------------------------------------------------------

    /// <summary>Renders a target-agnostic doc string as a Java <c>/** … */</c> Javadoc block at <paramref name="indent"/> (a no-op when empty).</summary>
    internal static void WriteJavadoc(StringBuilder sb, string? doc, string indent)
    {
        if (string.IsNullOrEmpty(doc))
        {
            return;
        }

        sb.Append(indent).Append("/**\n");
        foreach (var line in doc.Split('\n'))
        {
            sb.Append(indent).Append(" *");
            if (line.Length > 0)
            {
                sb.Append(' ').Append(line);
            }

            sb.Append('\n');
        }

        sb.Append(indent).Append(" */\n");
    }

    /// <summary>Renders <paramref name="raw"/> as a Java double-quoted string literal (escaping backslash, quote, and the C0 whitespace escapes).</summary>
    internal static string JavaStringLiteral(string raw)
    {
        var sb = new StringBuilder(raw.Length + 2);
        sb.Append('"');
        foreach (var c in raw)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
