using System.Text;
using Koine.Compiler.Ast;
using Koine.Compiler.Emit.CSharp;

namespace Koine.Compiler.Emit.Php;

/// <summary>
/// Orchestration support for <see cref="PhpEmitter"/>: per-run state, the PHP PSR-4 file layout
/// (context namespace → DDD kind subfolder → PascalCase class file), the file-header writer
/// (<c>&lt;?php</c> + <c>declare(strict_types=1);</c> + namespace + use lines), and small shared
/// formatting helpers (docblocks, indentation).
/// </summary>
public sealed partial class PhpEmitter
{
    /// <summary>Four-space indent — the PHP conventional indent width.</summary>
    private const string Indent = "    ";

    /// <summary>The immutable per-emit state threaded through every emit method.</summary>
    internal sealed record PhpEmitContext(
        ModelIndex Index,
        IReadOnlyDictionary<string, string> EnumMemberToType,
        IReadOnlySet<string> AdditiveNeeds,
        IReadOnlyDictionary<string, IReadOnlySet<string>> ScalarNeeds);

    // -------------------------------------------------------------------------
    // File / PSR-4 layout
    // -------------------------------------------------------------------------

    /// <summary>DDD kind subfolders (mirrors the Python emitter's KindFolder).</summary>
    private static class KindFolder
    {
        public const string ValueObjects = "ValueObjects";
        public const string Entities = "Entities";
        public const string Enums = "Enums";
        public const string Events = "Events";
        public const string Repositories = "Repositories";
    }

    /// <summary>
    /// The PSR-4 output path for a type: <c>src/&lt;Context&gt;/&lt;Kind&gt;/&lt;ClassName&gt;.php</c>.
    /// Example: <c>Sales/Money</c> in <c>ValueObjects</c> → <c>src/Sales/ValueObjects/Money.php</c>.
    /// </summary>
    private static string PathFor(string contextName, string kindFolder, string typeName)
    {
        var ctx = PhpNaming.ToPascalCase(contextName);
        var cls = PhpNaming.ClassName(typeName);
        return $"src/{ctx}/{kindFolder}/{cls}.php";
    }

    // -------------------------------------------------------------------------
    // File-header writer
    // -------------------------------------------------------------------------

    /// <summary>
    /// Writes a PHP file header: <c>&lt;?php\ndeclare(strict_types=1);\n\nnamespace Koine\…;\n</c>
    /// followed by any <c>use</c> declarations derived from the body, then the body itself.
    /// </summary>
    private static string Assemble(string contextName, string kindFolder, string body, string className)
    {
        var phpNs = PhpNaming.Namespace(contextName);
        if (kindFolder.Length > 0)
        {
            phpNs += "\\" + kindFolder;
        }

        var sb = new StringBuilder();
        sb.Append("<?php\n");
        sb.Append("// <auto-generated/>\n");
        sb.Append("declare(strict_types=1);\n");
        sb.Append('\n');
        sb.Append("namespace ").Append(phpNs).Append(";\n");

        // Collect use lines that the body actually references.
        var uses = CollectUses(body, className);
        if (uses.Count > 0)
        {
            sb.Append('\n');
            foreach (var use in uses)
            {
                sb.Append("use ").Append(use).Append(";\n");
            }
        }

        sb.Append('\n');
        sb.Append(body);
        if (!body.EndsWith('\n'))
        {
            sb.Append('\n');
        }
        return sb.ToString();
    }

    /// <summary>
    /// Collects the <c>use</c> import lines needed by a PHP class body.
    /// Scans for known runtime symbols (fully-qualified <c>\Koine\Runtime\…</c>)
    /// and emits a <c>use</c> alias so body code can reference the short name.
    /// Currently only the runtime types need importing (user types share the same namespace).
    /// </summary>
    private static List<string> CollectUses(string body, string className)
    {
        // We emit fully-qualified names in the body for the runtime (e.g. \Koine\Runtime\Decimal,
        // \Koine\Runtime\DomainInvariantViolationException), so no `use` import is strictly required.
        // Return an empty list — the body already uses FQNs everywhere.
        return new List<string>();
    }

    // -------------------------------------------------------------------------
    // Doc-comment helpers
    // -------------------------------------------------------------------------

    /// <summary>Writes a PHPDoc block for a class or member at <paramref name="indent"/>.</summary>
    private static void WriteDoc(StringBuilder sb, string? doc, string indent)
    {
        if (string.IsNullOrEmpty(doc))
        {
            return;
        }

        var lines = doc.Split('\n');
        if (lines.Length == 1)
        {
            sb.Append(indent).Append("/** ").Append(EscapeDoc(lines[0])).Append(" */\n");
            return;
        }

        sb.Append(indent).Append("/**\n");
        foreach (var line in lines)
        {
            sb.Append(indent).Append(" * ").Append(EscapeDoc(line)).Append('\n');
        }
        sb.Append(indent).Append(" */\n");
    }

    private static string EscapeDoc(string line) =>
        line.Replace("*/", "* /");

    /// <summary>A PHP double-quoted string literal for an invariant rule message.</summary>
    private static string RuleLiteral(string rule) =>
        "\"" + rule.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    // -------------------------------------------------------------------------
    // Enum member map, for translator qualification
    // -------------------------------------------------------------------------

    private static Dictionary<string, string> BuildEnumMemberMap(KoineModel model)
    {
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (ContextNode ctx in model.Contexts)
        {
            foreach (EnumDecl @enum in ctx.AllTypeDecls().OfType<EnumDecl>())
            {
                foreach (var member in @enum.MemberNames)
                {
                    map.TryAdd(member, @enum.Name);
                }
            }
        }
        return map;
    }
}
