namespace Koine.Compiler.Emit.Php;

/// <summary>
/// The once-emitted PHP runtime support, the analogue of the C# emitter's <c>Koine.Runtime</c>
/// files and the Python emitter's <c>koine_runtime.py</c>. It is written to a single
/// <c>KoineRuntime.php</c> at the output root and provides the shared domain primitives every
/// generated module uses:
/// <list type="bullet">
/// <item><c>DomainInvariantViolationException</c> — thrown when an invariant or illegal state
/// transition fails (carries the offending type name and rule).</item>
/// <item><c>ConcurrencyConflictException</c> — thrown on an optimistic-concurrency version mismatch.</item>
/// <item><c>Range</c> — a closed interval over an orderable type, with containment and overlap.</item>
/// <item><c>Decimal</c> — a string-backed arbitrary-precision decimal (no float).</item>
/// </list>
/// The contents are fixed string constants (no per-model state), so emission is deterministic and
/// byte-identical across runs. All files are dependency-free (PHP built-ins only, no Composer deps).
/// </summary>
internal static class PhpRuntime
{
    /// <summary>The emitted runtime file path, at the output root.</summary>
    public const string FileName = "KoineRuntime.php";

    /// <summary>The PHP namespace of the runtime module (<c>use Koine\Runtime\…</c>).</summary>
    public const string Namespace = "Koine\\Runtime";

    /// <summary>The full source of the runtime module.</summary>
    public const string Source =
        "<?php\n" +
        "// <auto-generated/>\n" +
        "// Koine PHP runtime: shared domain primitives, emitted once.\n" +
        "declare(strict_types=1);\n" +
        "\n" +
        "namespace Koine\\Runtime;\n" +
        "\n" +
        "use \\InvalidArgumentException;\n" +
        "use \\RuntimeException;\n" +
        "\n" +
        "/**\n" +
        " * Thrown when a domain invariant or illegal state transition is violated.\n" +
        " */\n" +
        "class DomainInvariantViolationException extends RuntimeException\n" +
        "{\n" +
        "    public function __construct(\n" +
        "        public readonly string $typeName,\n" +
        "        public readonly string $rule,\n" +
        "    ) {\n" +
        "        parent::__construct(\"Invariant violated on {$typeName}: {$rule}\");\n" +
        "    }\n" +
        "}\n" +
        "\n" +
        "/**\n" +
        " * Thrown when an optimistic-concurrency version check fails on a versioned aggregate.\n" +
        " */\n" +
        "class ConcurrencyConflictException extends RuntimeException\n" +
        "{\n" +
        "    public function __construct(\n" +
        "        public readonly string $typeName,\n" +
        "        public readonly int $expected,\n" +
        "        public readonly int $actual,\n" +
        "    ) {\n" +
        "        parent::__construct(\n" +
        "            \"Concurrency conflict on {$typeName}: expected version {$expected}, was {$actual}\"\n" +
        "        );\n" +
        "    }\n" +
        "}\n" +
        "\n" +
        "/**\n" +
        " * A closed interval [start, end] over an orderable value, with containment and overlap.\n" +
        " *\n" +
        " * The comparator is optional: when absent the default PHP comparison operators (`<`, `<=`)\n" +
        " * are used, which work for int, float, and string. Supply a callable(mixed,mixed):int\n" +
        " * (negative / zero / positive) for custom ordering, e.g. on value objects.\n" +
        " *\n" +
        " * @template T\n" +
        " */\n" +
        "class Range\n" +
        "{\n" +
        "    /** @param T $start\n" +
        "     * @param T $end\n" +
        "     * @param (callable(T,T):int)|null $comparator\n" +
        "     */\n" +
        "    public function __construct(\n" +
        "        public readonly mixed $start,\n" +
        "        public readonly mixed $end,\n" +
        "        private readonly mixed $comparator = null,\n" +
        "    ) {\n" +
        "        if ($this->cmp($start, $end) > 0) {\n" +
        "            throw new DomainInvariantViolationException(\n" +
        "                'Range',\n" +
        "                'start must be less than or equal to end',\n" +
        "            );\n" +
        "        }\n" +
        "    }\n" +
        "\n" +
        "    /** @param T $a @param T $b */\n" +
        "    private function cmp(mixed $a, mixed $b): int\n" +
        "    {\n" +
        "        if ($this->comparator !== null) {\n" +
        "            return ($this->comparator)($a, $b);\n" +
        "        }\n" +
        "        return $a <=> $b;\n" +
        "    }\n" +
        "\n" +
        "    /** Returns true when $value lies within [start, end] inclusive.\n" +
        "     * @param T $value\n" +
        "     */\n" +
        "    public function contains(mixed $value): bool\n" +
        "    {\n" +
        "        return $this->cmp($value, $this->start) >= 0\n" +
        "            && $this->cmp($value, $this->end) <= 0;\n" +
        "    }\n" +
        "\n" +
        "    /** Returns true when this range shares at least one point with $other.\n" +
        "     * @param Range<T> $other\n" +
        "     */\n" +
        "    public function overlaps(self $other): bool\n" +
        "    {\n" +
        "        return $this->cmp($this->start, $other->end) <= 0\n" +
        "            && $this->cmp($other->start, $this->end) <= 0;\n" +
        "    }\n" +
        "}\n" +
        "\n" +
        "/**\n" +
        " * A string-backed arbitrary-precision decimal value (no float).\n" +
        " *\n" +
        " * Arithmetic delegates to PHP's BCMath extension (bcadd, bcsub, bcmul, bcdiv).\n" +
        " * The scale (number of decimal places) defaults to 10; supply a higher value for\n" +
        " * use-cases that demand finer precision.\n" +
        " */\n" +
        "class Decimal\n" +
        "{\n" +
        "    /** @var numeric-string The validated decimal string; numeric by construction. */\n" +
        "    private string $value;\n" +
        "\n" +
        "    public function __construct(string|int $value, private readonly int $scale = 10)\n" +
        "    {\n" +
        "        $normalized = (string)$value;\n" +
        "        if (!is_numeric($normalized)) {\n" +
        "            throw new InvalidArgumentException(\"Invalid Decimal value: {$value}\");\n" +
        "        }\n" +
        "        // is_numeric() above narrows $normalized to numeric-string, which the bc-math\n" +
        "        // helpers (bcadd/bcsub/bcmul/bcdiv/bccomp) require under phpstan --level max.\n" +
        "        $this->value = $normalized;\n" +
        "    }\n" +
        "\n" +
        "    public function getValue(): string\n" +
        "    {\n" +
        "        return $this->value;\n" +
        "    }\n" +
        "\n" +
        "    public function add(self $other): self\n" +
        "    {\n" +
        "        return new self(bcadd($this->value, $other->value, $this->scale), $this->scale);\n" +
        "    }\n" +
        "\n" +
        "    public function sub(self $other): self\n" +
        "    {\n" +
        "        return new self(bcsub($this->value, $other->value, $this->scale), $this->scale);\n" +
        "    }\n" +
        "\n" +
        "    public function mul(self $other): self\n" +
        "    {\n" +
        "        return new self(bcmul($this->value, $other->value, $this->scale), $this->scale);\n" +
        "    }\n" +
        "\n" +
        "    public function div(self $other): self\n" +
        "    {\n" +
        "        if (bccomp($other->value, '0', $this->scale) === 0) {\n" +
        "            throw new DomainInvariantViolationException('Decimal', 'division by zero');\n" +
        "        }\n" +
        "        return new self(bcdiv($this->value, $other->value, $this->scale), $this->scale);\n" +
        "    }\n" +
        "\n" +
        "    public function compareTo(self $other): int\n" +
        "    {\n" +
        "        return bccomp($this->value, $other->value, $this->scale);\n" +
        "    }\n" +
        "\n" +
        "    public function equals(self $other): bool\n" +
        "    {\n" +
        "        return $this->compareTo($other) === 0;\n" +
        "    }\n" +
        "\n" +
        "    public function __toString(): string\n" +
        "    {\n" +
        "        return $this->value;\n" +
        "    }\n" +
        "\n" +
        "    /**\n" +
        "     * Sums a non-empty array of decimals, folding under add() from the first element.\n" +
        "     *\n" +
        "     * A string-backed decimal has no implicit zero, so an EMPTY array raises a domain error\n" +
        "     * rather than fabricating one (parity with the C#/TypeScript/Python empty-fold guard).\n" +
        "     * A value-object projection whose add() returns its own type folds here too.\n" +
        "     *\n" +
        "     * @param array<self> $values\n" +
        "     */\n" +
        "    public static function sum(array $values): self\n" +
        "    {\n" +
        "        if ($values === []) {\n" +
        "            throw new DomainInvariantViolationException('collection', 'cannot sum an empty collection (no zero value)');\n" +
        "        }\n" +
        "        $items = array_values($values);\n" +
        "        $total = $items[0];\n" +
        "        $count = count($items);\n" +
        "        for ($i = 1; $i < $count; $i++) {\n" +
        "            $total = $total->add($items[$i]);\n" +
        "        }\n" +
        "        return $total;\n" +
        "    }\n" +
        "\n" +
        "    /**\n" +
        "     * The minimum element of a non-empty array, ordered via compareTo().\n" +
        "     *\n" +
        "     * An EMPTY array raises a domain error (a collection with no element has no minimum),\n" +
        "     * mirroring the C#/TypeScript/Python empty-fold guard.\n" +
        "     *\n" +
        "     * @param array<self> $values\n" +
        "     */\n" +
        "    public static function min(array $values): self\n" +
        "    {\n" +
        "        if ($values === []) {\n" +
        "            throw new DomainInvariantViolationException('collection', 'cannot take min of an empty collection (no value)');\n" +
        "        }\n" +
        "        $items = array_values($values);\n" +
        "        $result = $items[0];\n" +
        "        $count = count($items);\n" +
        "        for ($i = 1; $i < $count; $i++) {\n" +
        "            if ($items[$i]->compareTo($result) < 0) {\n" +
        "                $result = $items[$i];\n" +
        "            }\n" +
        "        }\n" +
        "        return $result;\n" +
        "    }\n" +
        "\n" +
        "    /**\n" +
        "     * The maximum element of a non-empty array, ordered via compareTo().\n" +
        "     *\n" +
        "     * An EMPTY array raises a domain error (a collection with no element has no maximum),\n" +
        "     * mirroring the C#/TypeScript/Python empty-fold guard.\n" +
        "     *\n" +
        "     * @param array<self> $values\n" +
        "     */\n" +
        "    public static function max(array $values): self\n" +
        "    {\n" +
        "        if ($values === []) {\n" +
        "            throw new DomainInvariantViolationException('collection', 'cannot take max of an empty collection (no value)');\n" +
        "        }\n" +
        "        $items = array_values($values);\n" +
        "        $result = $items[0];\n" +
        "        $count = count($items);\n" +
        "        for ($i = 1; $i < $count; $i++) {\n" +
        "            if ($items[$i]->compareTo($result) > 0) {\n" +
        "                $result = $items[$i];\n" +
        "            }\n" +
        "        }\n" +
        "        return $result;\n" +
        "    }\n" +
        "}\n" +
        "\n" +
        "/**\n" +
        " * Generic query-handler contract: handles a typed query and returns a typed result.\n" +
        " *\n" +
        " * Implement this interface for each query handler in the application layer.\n" +
        " *\n" +
        " * @template TQuery\n" +
        " * @template TResult\n" +
        " */\n" +
        "interface QueryHandler\n" +
        "{\n" +
        "    /** @param TQuery $query @return TResult */\n" +
        "    public function handle(mixed $query): mixed;\n" +
        "}\n";

    /// <summary>
    /// A minimal PSR-4 <c>composer.json</c> for the generated package.
    /// Maps <c>Koine\</c> to <c>src/</c> so the autoloader finds the generated code.
    /// In JSON the backslash is escaped, so the key appears as <c>"Koine\\"</c> in the file.
    /// </summary>
    public const string ComposerJson =
        "{\n" +
        "    \"name\": \"koine/generated\",\n" +
        "    \"description\": \"Generated by Koine — do not edit by hand.\",\n" +
        "    \"type\": \"library\",\n" +
        "    \"require\": {\n" +
        "        \"php\": \">=8.1\"\n" +
        "    },\n" +
        "    \"autoload\": {\n" +
        "        \"psr-4\": {\n" +
        "            \"Koine\\\\\": \"src/\"\n" +
        "        }\n" +
        "    },\n" +
        "    \"config\": {\n" +
        "        \"sort-packages\": true\n" +
        "    }\n" +
        "}\n";

    /// <summary>
    /// A <c>phpstan.neon</c> at the strictest level (max), scanning the generated <c>src/</c> tree.
    /// </summary>
    public const string PhpStanNeon =
        "# <auto-generated/>\n" +
        "parameters:\n" +
        "    level: max\n" +
        "    paths:\n" +
        "        - src\n";
}
