namespace Koine.Compiler.Emit.Rust;

/// <summary>
/// The fixed-string runtime for the generated Rust crate, emitted once at <c>src/koine_runtime.rs</c>
/// (the Rust analogue of <see cref="Python.PyRuntime"/> / <c>TsRuntime</c>). It supplies the handful
/// of shared symbols the emitted modules reference: the money-safe <c>Decimal</c> re-export, an
/// <c>Instant</c> timestamp alias plus <c>now()</c>, the <c>Range</c> interval value type, decimal-safe
/// fold helpers (<c>koine_sum</c>/<c>koine_min</c>/<c>koine_max</c>), and an unanchored regex matcher.
/// Everything here is dependency-light — only <c>rust_decimal</c> (money) and <c>regex</c> (the
/// <c>matches</c> operator) are external; the rest is <c>std</c>.
/// </summary>
internal static class RustRuntime
{
    /// <summary>The runtime module's file path within the emitted crate.</summary>
    public const string FileName = "src/koine_runtime.rs";

    /// <summary>The crate-relative module name the generated code imports from.</summary>
    public const string ModuleName = "koine_runtime";

    /// <summary>The runtime module source (no trailing newline; the emitter adds one).</summary>
    public const string Source =
        """
        // <auto-generated/>
        //! Shared runtime support for the generated domain crate. Hand-edits will be overwritten.

        #![allow(dead_code)]

        /// Money-safe fixed-point decimal. Re-exported so generated modules can `use
        /// crate::koine_runtime::Decimal;` without naming the backing crate.
        pub use rust_decimal::Decimal;

        /// A point in time. Aliased to the standard wall-clock type so the crate stays dependency-light.
        pub type Instant = std::time::SystemTime;

        /// The current instant (the Koine `now` value builtin).
        pub fn now() -> Instant {
            std::time::SystemTime::now()
        }

        /// Parses a decimal literal at its exact textual form (money-safe, never via `f64`).
        pub fn dec(text: &str) -> Decimal {
            Decimal::from_str_exact(text).expect("invalid decimal literal")
        }

        /// A closed interval `[start, end]` over an ordered type — the Koine `Range<T>`.
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub struct Range<T: PartialOrd> {
            start: T,
            end: T,
        }

        impl<T: PartialOrd> Range<T> {
            /// Creates an interval. The caller is responsible for `start <= end` (a domain invariant).
            pub fn new(start: T, end: T) -> Self {
                Self { start, end }
            }

            pub fn start(&self) -> &T {
                &self.start
            }

            pub fn end(&self) -> &T {
                &self.end
            }

            /// True when `value` lies within the closed interval.
            pub fn contains(&self, value: &T) -> bool {
                *value >= self.start && *value <= self.end
            }

            /// True when this interval and `other` share at least one point.
            pub fn overlaps(&self, other: &Range<T>) -> bool {
                self.start <= other.end && other.start <= self.end
            }
        }

        /// Unanchored regex test (the Koine `matches /pattern/` operator). A malformed pattern — which
        /// the compiler's regex validation rejects upstream — conservatively yields `false`.
        pub fn regex_is_match(pattern: &str, input: &str) -> bool {
            regex::Regex::new(pattern).map(|re| re.is_match(input)).unwrap_or(false)
        }

        /// Decimal-safe sum over a non-empty iterator (the Koine `.sum(...)` fold). Panics on an empty
        /// input, mirroring the seedless-fold behaviour of the C#/TypeScript/Python emitters.
        pub fn koine_sum<T>(items: impl IntoIterator<Item = T>) -> T
        where
            T: std::ops::Add<Output = T>,
        {
            items
                .into_iter()
                .reduce(|acc, x| acc + x)
                .expect("sum of an empty collection")
        }

        /// The minimum of a non-empty iterator (the Koine `.min(...)` fold).
        pub fn koine_min<T: PartialOrd>(items: impl IntoIterator<Item = T>) -> T {
            items
                .into_iter()
                .reduce(|acc, x| if x < acc { x } else { acc })
                .expect("min of an empty collection")
        }

        /// The maximum of a non-empty iterator (the Koine `.max(...)` fold).
        pub fn koine_max<T: PartialOrd>(items: impl IntoIterator<Item = T>) -> T {
            items
                .into_iter()
                .reduce(|acc, x| if x > acc { x } else { acc })
                .expect("max of an empty collection")
        }
        """;

    /// <summary>
    /// The <c>Cargo.toml</c> for the generated crate — <c>rust_decimal</c> (money) + <c>regex</c> (the
    /// <c>matches</c> operator), the lib target, and — only when <paramref name="withUuid"/> — the
    /// <c>uuid</c> crate, pulled in solely to generate aggregate-factory identities (a v4 UUID). A
    /// model with no factory keeps the dependency-light two-crate manifest.
    /// </summary>
    public static string CargoToml(bool withUuid = false)
    {
        var uuidDep = withUuid ? "uuid = { version = \"1\", features = [\"v4\"] }\n" : string.Empty;
        return
            "# <auto-generated/>\n" +
            "[package]\n" +
            "name = \"koine-domain\"\n" +
            "version = \"0.0.0\"\n" +
            "edition = \"2021\"\n" +
            "description = \"Generated by Koine — do not edit by hand.\"\n" +
            "\n" +
            "[dependencies]\n" +
            "rust_decimal = \"1\"\n" +
            "regex = \"1\"\n" +
            uuidDep +
            "\n" +
            "[lib]\n" +
            "path = \"src/lib.rs\"";
    }
}
