using System.Text;
using System.Text.RegularExpressions;
using Koine.Compiler.Ast;

namespace Koine.Compiler.Emit.Rust;

/// <summary>
/// Orchestration support for <see cref="RustEmitter"/>: the per-emit state threaded through the
/// construct emitters, the per-module <c>use</c>-header assembler (each context module imports only the
/// runtime/std symbols its body actually references — the same data-driven approach as the C#
/// <c>UsingCollector</c> and the Python <c>Assemble</c>), the generated per-context <c>DomainError</c>
/// enum, the crate <c>lib.rs</c>, and small shared formatting helpers.
/// </summary>
public sealed partial class RustEmitter
{
    /// <summary>The immutable per-emit state threaded through every emit method.</summary>
    internal sealed record RustEmitContext(
        ModelIndex Index,
        IReadOnlyDictionary<string, string> EnumMemberToType,
        IReadOnlySet<string> AdditiveNeeds,
        IReadOnlyDictionary<string, IReadOnlySet<string>> ScalarNeeds);

    internal const string Indent = "    ";

    private static readonly Regex IdentifierRegex = new(@"\b[A-Za-z_][A-Za-z0-9_]*\b", RegexOptions.Compiled);

    /// <summary>The snake_case Rust module name for a bounded context (remapped via options).</summary>
    private string ModuleNameFor(string context) => _options.RemapModule(RustNaming.ToSnakeCase(context));

    // ----------------------------------------------------------------------
    // Per-module use-header assembly
    // ----------------------------------------------------------------------

    /// <summary>
    /// Wraps a rendered context-module body with its <c>use</c> header and an
    /// <c>// &lt;auto-generated/&gt;</c> banner. The import set is derived from the identifiers that
    /// actually appear in the body (line comments stripped first so a type named only in a doc comment
    /// never drives a spurious import). Deterministic: the use lines are emitted in a fixed order.
    /// </summary>
    private string Assemble(string body, string? moduleDoc = null)
    {
        var codeView = StripComments(body);
        var present = new HashSet<string>(StringComparer.Ordinal);
        foreach (Match m in IdentifierRegex.Matches(codeView))
        {
            present.Add(m.Value);
        }

        var uses = new List<string>();
        if (present.Contains("Decimal"))
        {
            uses.Add("use crate::koine_runtime::Decimal;");
        }
        if (present.Contains("Instant"))
        {
            uses.Add("use crate::koine_runtime::Instant;");
        }
        if (present.Contains("Range"))
        {
            uses.Add("use crate::koine_runtime::Range;");
        }
        if (present.Contains("HashMap"))
        {
            uses.Add("use std::collections::HashMap;");
        }
        if (present.Contains("HashSet"))
        {
            uses.Add("use std::collections::HashSet;");
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        if (!string.IsNullOrEmpty(moduleDoc))
        {
            // Inner module docs must precede items, so they go ahead of the `use` header.
            sb.Append(moduleDoc).Append('\n');
        }
        sb.Append('\n');
        if (uses.Count > 0)
        {
            foreach (var u in uses)
            {
                sb.Append(u).Append('\n');
            }
            sb.Append('\n');
        }

        sb.Append(body);
        if (!body.EndsWith('\n'))
        {
            sb.Append('\n');
        }
        return sb.ToString();
    }

    /// <summary>A code-only view of a module body with <c>//</c> line comments removed.</summary>
    private static string StripComments(string body)
    {
        var sb = new StringBuilder(body.Length);
        foreach (var line in body.Split('\n'))
        {
            var idx = line.IndexOf("//", StringComparison.Ordinal);
            sb.Append(idx >= 0 ? line[..idx] : line).Append('\n');
        }
        return sb.ToString();
    }

    // ----------------------------------------------------------------------
    // Per-context DomainError enum
    // ----------------------------------------------------------------------

    /// <summary>
    /// The per-context <c>DomainError</c> enum returned by every smart constructor and mutating
    /// behavior. One <c>InvariantViolation</c> variant carries the violated type name and rule text;
    /// a <c>UnitMismatch</c> variant supports the unit-checked quantity arithmetic.
    /// </summary>
    private static void WriteDomainError(StringBuilder sb)
    {
        sb.Append("/// The errors a domain operation in this context can fail with.\n");
        sb.Append("#[derive(Debug, Clone, PartialEq, Eq)]\n");
        sb.Append("pub enum DomainError {\n");
        sb.Append(Indent).Append("/// An invariant of `type_name` was violated: `rule`.\n");
        sb.Append(Indent).Append("InvariantViolation { type_name: &'static str, rule: &'static str },\n");
        sb.Append(Indent).Append("/// Two quantities of different units were combined.\n");
        sb.Append(Indent).Append("UnitMismatch { type_name: &'static str },\n");
        sb.Append("}\n\n");

        sb.Append("impl std::fmt::Display for DomainError {\n");
        sb.Append(Indent).Append("fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
        sb.Append(Indent).Append(Indent).Append("match self {\n");
        sb.Append(Indent).Append(Indent).Append(Indent)
          .Append("DomainError::InvariantViolation { type_name, rule } => write!(f, \"{type_name}: {rule}\"),\n");
        sb.Append(Indent).Append(Indent).Append(Indent)
          .Append("DomainError::UnitMismatch { type_name } => write!(f, \"{type_name}: units do not match\"),\n");
        sb.Append(Indent).Append(Indent).Append("}\n");
        sb.Append(Indent).Append("}\n");
        sb.Append("}\n\n");

        sb.Append("impl std::error::Error for DomainError {}\n");
    }

    // ----------------------------------------------------------------------
    // lib.rs
    // ----------------------------------------------------------------------

    /// <summary>The crate root: declares the runtime module and one public module per context.</summary>
    private string EmitLibRs(KoineModel model)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("//! Generated domain crate. Hand-edits will be overwritten.\n\n");
        sb.Append("pub mod ").Append(RustRuntime.ModuleName).Append(";\n");
        foreach (var module in model.Contexts.Select(c => ModuleNameFor(c.Name)).OrderBy(m => m, StringComparer.Ordinal))
        {
            sb.Append("pub mod ").Append(module).Append(";\n");
        }
        return sb.ToString();
    }

    // ----------------------------------------------------------------------
    // Enum member map (member name -> owning enum), for translator qualification
    // ----------------------------------------------------------------------

    private static Dictionary<string, string> BuildEnumMemberMap(KoineModel model)
    {
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (ContextNode ctx in model.Contexts)
        {
            foreach (EnumDecl @enum in ctx.AllTypeDecls().OfType<EnumDecl>())
            {
                foreach (var member in @enum.MemberNames)
                {
                    map.TryAdd(member, @enum.Name);
                }
            }
        }
        return map;
    }

    // ----------------------------------------------------------------------
    // Formatting helpers
    // ----------------------------------------------------------------------

    /// <summary>Renders a target-agnostic doc string as Rust <c>///</c> doc comments at <paramref name="indent"/>.</summary>
    internal static void WriteDoc(StringBuilder sb, string? doc, string indent)
    {
        if (string.IsNullOrEmpty(doc))
        {
            return;
        }

        foreach (var line in doc.Split('\n'))
        {
            sb.Append(indent).Append("///");
            if (line.Length > 0)
            {
                sb.Append(' ').Append(line);
            }
            sb.Append('\n');
        }
    }

    /// <summary>A Rust string literal for an invariant rule message (escaped, double-quoted).</summary>
    internal static string RuleLiteral(string rule) =>
        "\"" + rule.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
