// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';
import starlightBlog from 'starlight-blog';
import mermaid from 'astro-mermaid';

import koineGrammar from './src/grammars/koine.tmLanguage.json' with { type: 'json' };

// Absolute URL of the deployed social-share card (generated by scripts/og-image.mjs).
// Used for og:image / twitter:image on every page so links unfurl with a branded preview.
const OG_IMAGE = 'https://atypical-consulting.github.io/Koine/og.png';

// Register the repo's TextMate grammar so ```koine fenced blocks get real syntax
// highlighting (keywords, types, invariants, regex literals, …).
const koineLang = {
	...koineGrammar,
	name: 'koine',
	scopeName: 'source.koine',
	aliases: ['koi'],
};

// https://astro.build/config
export default defineConfig({
	// Project pages site for the Atypical-Consulting/Koine repository.
	site: 'https://atypical-consulting.github.io',
	base: '/Koine/',
	// Emit clean, trailing-slash URLs so canonical links and the sitemap agree.
	trailingSlash: 'always',
	integrations: [
		// Render ```mermaid fences (emitted by the `docs` target) as live SVG diagrams with
		// light/dark theme switching. MUST come before Starlight so its rehype pass claims the
		// mermaid fences before Expressive Code turns them into plain highlighted code blocks.
		mermaid({ theme: 'neutral', autoTheme: true }),
		sitemap(),
		starlight({
			title: 'Koine',
			description:
				'Koine is a domain-specific language for Domain-Driven Design: write the ubiquitous language once in .koi files and generate idiomatic, self-contained C# (and TypeScript) — value objects, entities, aggregates, invariants, commands, events, state machines, CQRS and context maps.',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/Atypical-Consulting/Koine' },
			],
			plugins: [
				starlightBlog({
					title: 'Blog',
					authors: {
						phmatray: {
							name: 'Philippe Matray',
							title: 'Creator of Koine',
							picture: 'https://github.com/phmatray.png',
							url: 'https://github.com/phmatray',
						},
					},
				}),
			],
			// Starlight emits canonical/OpenGraph/Twitter tags itself, but not a social image.
			// Add og:image + twitter:image globally so docs links unfurl with the brand card.
			head: [
				{ tag: 'meta', attrs: { property: 'og:image', content: OG_IMAGE } },
				{ tag: 'meta', attrs: { property: 'og:image:width', content: '1200' } },
				{ tag: 'meta', attrs: { property: 'og:image:height', content: '630' } },
				{
					tag: 'meta',
					attrs: { property: 'og:image:alt', content: 'Koine — model the domain, compile the code' },
				},
				{ tag: 'meta', attrs: { name: 'twitter:image', content: OG_IMAGE } },
			],
			expressiveCode: {
				shiki: { langs: [koineLang] },
			},
			// Light blueprint brand pass over the docs (accent + display/mono fonts), kept
			// separate from Starlight's body readability. See src/styles/brand.css.
			customCss: ['./src/styles/brand.css'],
			editLink: {
				baseUrl: 'https://github.com/Atypical-Consulting/Koine/edit/main/website/',
			},
			sidebar: [
				{
					// Link out to the custom (non-Starlight) Playground page.
					label: '▸ Playground',
					link: '/playground/',
				},
				{
					// Link out to the hosted web edition of Koine Studio (the full browser IDE).
					label: '▸ Studio',
					link: '/studio/',
				},
				{
					label: 'Start here',
					items: [
						{ label: 'What is Koine?', slug: 'start/what-is-koine' },
						{ label: 'Installation', slug: 'start/installation' },
						{ label: 'Your first model', slug: 'start/your-first-model' },
						{ label: 'Reading the generated C#', slug: 'start/reading-the-output' },
					],
				},
				{
					label: 'Tutorials',
					items: [
						{ label: '1 · Values & invariants', slug: 'tutorials/values-and-invariants' },
						{ label: '2 · Entities & aggregates', slug: 'tutorials/entities-and-aggregates' },
						{ label: '3 · Commands, events & state', slug: 'tutorials/commands-events-state' },
						{ label: '4 · The application layer', slug: 'tutorials/application-layer' },
						{ label: '5 · Many bounded contexts', slug: 'tutorials/multiple-contexts' },
						{ label: '6 · Evolving a model', slug: 'tutorials/evolving-a-model' },
					],
				},
				{
					label: 'Language reference',
					items: [
						{ label: 'Overview', slug: 'reference/overview' },
						{ label: 'Contexts & types', slug: 'reference/contexts-and-types' },
						{ label: 'Value objects', slug: 'reference/value-objects' },
						{ label: 'Entities & identity', slug: 'reference/entities-and-identity' },
						{ label: 'Aggregates', slug: 'reference/aggregates' },
						{ label: 'Enums', slug: 'reference/enums' },
						{ label: 'Expressions', slug: 'reference/expressions' },
						{ label: 'Invariants', slug: 'reference/invariants' },
						{ label: 'Commands, events & state machines', slug: 'reference/commands-events-state' },
						{ label: 'Factories', slug: 'reference/factories' },
						{ label: 'Specs, services & policies', slug: 'reference/specs-services-policies' },
						{ label: 'Repositories & concurrency', slug: 'reference/repositories-concurrency' },
						{ label: 'Application layer & CQRS', slug: 'reference/application-cqrs' },
						{ label: 'Multi-file, imports & modules', slug: 'reference/multi-file-imports-modules' },
						{ label: 'Context maps & integration', slug: 'reference/context-maps-integration' },
						{ label: 'Versioning & evolution', slug: 'reference/versioning' },
						{ label: 'Templates', slug: 'reference/templates' },
					],
				},
				{
					// Living documentation generated from the Pizzeria template
					// (templates/pizzeria) by scripts/build-docs.mjs (the `docs` emitter).
					// Regenerated on every build; the pages live under
					// src/content/docs/reference/domain/ (gitignored).
					label: 'Domain reference (generated)',
					items: [
						{ label: 'Overview', slug: 'reference/domain' },
						{ label: 'Menu', slug: 'reference/domain/menu' },
						{ label: 'Ordering', slug: 'reference/domain/ordering' },
						{ label: 'Kitchen', slug: 'reference/domain/kitchen' },
						{ label: 'Delivery', slug: 'reference/domain/delivery' },
						{ label: 'Payment', slug: 'reference/domain/payment' },
						{ label: 'Promotions', slug: 'reference/domain/promotions' },
						{ label: 'Gateway', slug: 'reference/domain/gateway' },
						{ label: 'Context map', slug: 'reference/domain/context-map' },
						{ label: 'Integration events', slug: 'reference/domain/integration-events' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Feature catalogue (R1–R17)', slug: 'guides/feature-catalogue' },
						{ label: 'CLI reference', slug: 'guides/cli' },
						{ label: 'Architecture', slug: 'guides/architecture' },
						{ label: 'Koine as a platform', slug: 'guides/platform' },
						{ label: 'Editor tooling', slug: 'guides/editor-tooling' },
						{ label: 'Koine Studio', slug: 'guides/koine-studio' },
						{ label: 'Local LLM in the Assistant', slug: 'guides/assistant-local-llm' },
						{ label: 'MCP server', slug: 'guides/mcp-server' },
						{ label: 'Model as spec', slug: 'guides/model-as-spec' },
						{ label: 'Roadmap', slug: 'guides/roadmap' },
					],
				},
			],
		}),
	],
});
