using Koine.Compiler.Emit;
using Koine.Compiler.Services;

namespace Koine.Compiler.Tests;

/// <summary>
/// The Java backend's smart-enum slice (issue #858, Task 5): a Koine <c>enum</c> emits as a Java
/// <c>enum</c>. A bare-name enum is just its constant list; a smart enum carrying associated data
/// (e.g. <c>GOLD(79, "Au")</c>) emits <c>private final</c> fields, a private canonical constructor, and
/// one public accessor per field — the Java idiom for an enum-with-data, mirroring the Rust/C# smart-enum
/// emission. These tests compile small Koine sources through <see cref="JavaEmitter"/> and pin the emitted
/// Java: the enum shape, the field/constructor/accessor members, the per-context package/path layout, the
/// keyword-named constant renaming, and — crucially — that the constant spelling matches what
/// <see cref="JavaExpressionTranslator"/> renders for an enum-constant reference (so a derived field that
/// compares against a constant keeps compiling).
/// </summary>
public class JavaEnumTests
{
    [Fact]
    public void A_smart_enum_emits_fields_a_private_constructor_and_accessors()
    {
        var metal = EmitTypeFile(
            "context Catalog {\n" +
            "  enum Metal(atomicNumber: Int, symbol: String) {\n" +
            "    GOLD(79, \"Au\")\n" +
            "    SILVER(47, \"Ag\")\n" +
            "  }\n" +
            "}\n",
            "Metal.java");

        // A Java enum whose constants invoke the canonical constructor with their associated literals
        // (Int -> a `long` literal, String -> a quoted literal). The last constant terminates with `;`.
        metal.ShouldContain("public enum Metal {");
        metal.ShouldContain("GOLD(79L, \"Au\"),");
        metal.ShouldContain("SILVER(47L, \"Ag\");");

        // One private final field per signature entry, a private canonical constructor assigning them,
        // and one public accessor per field.
        metal.ShouldContain("private final long atomicNumber;");
        metal.ShouldContain("private final String symbol;");
        metal.ShouldContain("private Metal(long atomicNumber, String symbol) {");
        metal.ShouldContain("this.atomicNumber = atomicNumber;");
        metal.ShouldContain("public long atomicNumber() {");
        metal.ShouldContain("public String symbol() {");
        metal.ShouldContain("return this.symbol;");

        // Laid out under the base package + lowercased context, with the auto-generated banner.
        metal.ShouldContain("// <auto-generated/>");
        metal.ShouldContain("package koine.generated.catalog;");
    }

    [Fact]
    public void A_smart_enum_file_lands_at_the_package_directory_path()
    {
        var path = EmitTypePath(
            "context Catalog {\n" +
            "  enum Metal(atomicNumber: Int, symbol: String) {\n" +
            "    GOLD(79, \"Au\")\n" +
            "  }\n" +
            "}\n",
            "Metal.java");

        path.ShouldBe("koine/generated/catalog/Metal.java");
    }

    [Fact]
    public void A_plain_enum_emits_the_bare_constant_list()
    {
        var mass = EmitTypeFile(
            "context Catalog {\n" +
            "  enum MassUnit { Gram, Kilogram }\n" +
            "}\n",
            "MassUnit.java");

        mass.ShouldContain("public enum MassUnit {");
        mass.ShouldContain("Gram,");
        mass.ShouldContain("Kilogram");

        // No associated data, so no field / constructor / accessor scaffolding.
        mass.ShouldNotContain("private final");
        mass.ShouldNotContain("private MassUnit(");
    }

    [Fact]
    public void A_keyword_named_member_is_renamed_with_a_trailing_underscore()
    {
        var slot = EmitTypeFile(
            "context Ordering {\n" +
            "  enum Slot { normal, default }\n" +
            "}\n",
            "Slot.java");

        slot.ShouldContain("public enum Slot {");
        slot.ShouldContain("normal,");
        // `default` is a Java reserved word, so the constant is renamed `default_` (Java has no inline escape).
        slot.ShouldContain("default_");
    }

    [Fact]
    public void A_constant_declaration_matches_the_translator_reference_spelling()
    {
        // Reconciliation: the enum constant `high` must be spelled identically where it is DECLARED (the
        // enum file) and where it is REFERENCED (a derived field comparing against it), or the reference
        // would not resolve. Both go through JavaNaming.EscapeIdentifier of the raw member name.
        const string source =
            "context Catalog {\n" +
            "  enum Priority { low, high }\n" +
            "  value Ticket {\n" +
            "    level: Priority\n" +
            "    urgent: Bool = level == high\n" +
            "  }\n" +
            "}\n";

        var priority = EmitTypeFile(source, "Priority.java");
        var ticket = EmitTypeFile(source, "Ticket.java");

        // Declared in the enum...
        priority.ShouldContain("high");
        // ...and referenced with the same spelling, qualified by the enum type, in the derived accessor.
        ticket.ShouldContain("Priority.high");
    }

    // ----------------------------------------------------------------------

    /// <summary>Compiles <paramref name="source"/> through the Java emitter and returns the contents of the type file ending in <paramref name="suffix"/>.</summary>
    private static string EmitTypeFile(string source, string suffix) => EmitFile(source, suffix).Contents;

    /// <summary>Compiles <paramref name="source"/> through the Java emitter and returns the relative path of the type file ending in <paramref name="suffix"/>.</summary>
    private static string EmitTypePath(string source, string suffix) => EmitFile(source, suffix).RelativePath;

    private static EmittedFile EmitFile(string source, string suffix)
    {
        var result = new KoineCompiler().Compile(source, new JavaEmitter());
        result.Success.ShouldBeTrue(string.Join("\n", result.Diagnostics.Select(d => d.ToString())));
        return result.Files.Single(f => f.RelativePath.EndsWith(suffix, StringComparison.Ordinal));
    }
}
