using Koine.Compiler.Emit;
using Koine.Compiler.Services;

namespace Koine.Compiler.Tests;

/// <summary>
/// The Java backend's value-object slice (issue #858, Task 4): a Koine <c>value</c> emits as a Java
/// <c>record</c> whose compact constructor runs the invariants, throwing
/// <c>koine.runtime.DomainException</c> on a violation — the record analogue of the Rust smart
/// constructor and the C# guarded constructor. These tests compile small Koine sources through
/// <see cref="JavaEmitter"/> and pin the emitted Java: the record shape, the per-context package/path
/// layout, the invariant guards (Decimal <c>compareTo</c> and <c>matches</c> regex lowerings), and the
/// optional/collection component normalizations.
/// </summary>
public class JavaValueObjectTests
{
    [Fact]
    public void Money_emits_a_validating_record_in_the_context_package()
    {
        var money = EmitTypeFile(
            "context Billing {\n" +
            "  value Money {\n" +
            "    amount: Decimal\n" +
            "    invariant amount >= 0  \"amount must be non-negative\"\n" +
            "  }\n" +
            "}\n",
            "Money.java");

        // The record header carries the single Decimal component (BigDecimal, money-safe).
        money.ShouldContain("public record Money(java.math.BigDecimal amount)");

        // The compact constructor guards the invariant, throwing DomainException when it does not hold.
        money.ShouldContain("public Money {");
        money.ShouldContain("if (!(amount.compareTo(java.math.BigDecimal.ZERO) >= 0)) {");
        money.ShouldContain("throw new koine.runtime.DomainException(\"amount must be non-negative\");");

        // Laid out under the base package + lowercased context, with the auto-generated banner.
        money.ShouldContain("// <auto-generated/>");
        money.ShouldContain("package koine.generated.billing;");
    }

    [Fact]
    public void Money_file_lands_at_the_package_directory_path()
    {
        var path = EmitTypePath(
            "context Billing {\n" +
            "  value Money {\n" +
            "    amount: Decimal\n" +
            "    invariant amount >= 0  \"amount must be non-negative\"\n" +
            "  }\n" +
            "}\n",
            "Money.java");

        path.ShouldBe("koine/generated/billing/Money.java");
    }

    [Fact]
    public void Email_lowers_a_matches_invariant_to_an_inline_regex_find()
    {
        var email = EmitTypeFile(
            "context Billing {\n" +
            "  value Email {\n" +
            "    raw: String\n" +
            "    invariant raw matches /^[^@]+@[^@]+$/  \"invalid email address\"\n" +
            "  }\n" +
            "}\n",
            "Email.java");

        email.ShouldContain("public record Email(String raw)");
        // A matches-invariant is a dependency-free, unanchored find, negated for the failure guard.
        email.ShouldContain(
            "if (!(java.util.regex.Pattern.compile(\"^[^@]+@[^@]+$\").matcher(raw).find())) {");
        email.ShouldContain("throw new koine.runtime.DomainException(\"invalid email address\");");
    }

    [Fact]
    public void A_multi_field_value_object_lists_every_component_in_order()
    {
        var money = EmitTypeFile(
            "context Billing {\n" +
            "  value Money {\n" +
            "    amount: Decimal\n" +
            "    currency: Currency\n" +
            "    invariant amount >= 0  \"amount must be non-negative\"\n" +
            "  }\n" +
            "  enum Currency { EUR, USD, GBP }\n" +
            "}\n",
            "Money.java");

        // Both components, in declaration order; the enum component keeps its Java type name.
        money.ShouldContain("public record Money(java.math.BigDecimal amount, Currency currency)");
    }

    [Fact]
    public void A_collection_component_is_copied_defensively_in_the_compact_constructor()
    {
        var basket = EmitTypeFile(
            "context Shopping {\n" +
            "  value Basket {\n" +
            "    items: List<String>\n" +
            "    invariant items.isNotEmpty  \"a basket cannot be empty\"\n" +
            "  }\n" +
            "}\n",
            "Basket.java");

        basket.ShouldContain("public record Basket(java.util.List<String> items)");
        // An unmodifiable defensive copy so the record cannot observe an externally-mutated list.
        basket.ShouldContain("items = java.util.List.copyOf(items);");
        basket.ShouldContain("if (!(!items.isEmpty())) {");
    }

    [Fact]
    public void An_optional_component_is_normalized_to_an_empty_optional()
    {
        var profile = EmitTypeFile(
            "context Accounts {\n" +
            "  value Profile {\n" +
            "    displayName: String\n" +
            "    nickname: String?\n" +
            "  }\n" +
            "}\n",
            "Profile.java");

        profile.ShouldContain("public record Profile(String displayName, java.util.Optional<String> nickname)");
        profile.ShouldContain("nickname = nickname == null ? java.util.Optional.empty() : nickname;");
    }

    // ----------------------------------------------------------------------

    /// <summary>Compiles <paramref name="source"/> through the Java emitter and returns the contents of the type file ending in <paramref name="suffix"/>.</summary>
    private static string EmitTypeFile(string source, string suffix) => EmitFile(source, suffix).Contents;

    /// <summary>Compiles <paramref name="source"/> through the Java emitter and returns the relative path of the type file ending in <paramref name="suffix"/>.</summary>
    private static string EmitTypePath(string source, string suffix) => EmitFile(source, suffix).RelativePath;

    private static EmittedFile EmitFile(string source, string suffix)
    {
        var result = new KoineCompiler().Compile(source, new JavaEmitter());
        result.Success.ShouldBeTrue(string.Join("\n", result.Diagnostics.Select(d => d.ToString())));
        return result.Files.Single(f => f.RelativePath.EndsWith(suffix, StringComparison.Ordinal));
    }
}
